'use client';
import { useEffect, useRef, useState } from 'react';
import type { createGame, MapId, HUD } from './race';
import {TownMinimap,TownFullMap} from './town-minimap';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
const maps={coast:{title:'Coastline circuit',location:'PACIFIC COAST',description:'Sweeping corners along the coast.',number:'01'},costco:{title:'Costco parking lot',location:'COSTCO WHOLESALE',description:'Wide-open bays. Long, icy slides.',number:'02'},svitlodarsk:{title:'Svitlodarsk',location:'SVITLODARSK · UKRAINE',description:'Tree-lined streets, shops & reservoirs.',number:'03'},wurzburg:{title:'Würzburg',location:'WÜRZBURG · GERMANY',description:'Hilly streets, vineyards & the Main river.',number:'04'}};
const isTown=(map:MapId)=>map==='svitlodarsk'||map==='wurzburg';
const townTag=(id:MapId)=>id==='svitlodarsk'?'NEW':id==='costco'?'LOT':id==='wurzburg'?'HILLS':'COAST';

export default function Home(){
 const mount=useRef<HTMLDivElement>(null);const game=useRef<ReturnType<typeof createGame>|null>(null);
const [ready,setReady]=useState(false),[started,setStarted]=useState(false),[paused,setPaused]=useState(false),[muted,setMuted]=useState(false),[error,setError]=useState('');
  const [map,setMap]=useState<MapId>('coast');const [fullMap,setFullMap]=useState(false);const fullMapRef=useRef(fullMap),startedRef=useRef(false);
  useEffect(()=>{startedRef.current=started},[started]);
  const toggleMap=(open?:boolean)=>{if(!startedRef.current)return;const next=open??!fullMapRef.current;fullMapRef.current=next;setFullMap(next);game.current?.setMapOpen(next)};
  useEffect(()=>{const h=(e:KeyboardEvent)=>{if(e.code==='KeyM'){e.preventDefault();toggleMap()}else if(e.code==='Escape'&&fullMapRef.current){e.preventDefault();toggleMap(false)}};window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h)},[]);
 const [hud,setHud]=useState<HUD>({speed:0,score:0,combo:0,angle:0,drifting:false,x:0,z:0,yaw:0,mode:'car',hint:'E · Get out of sports car',carX:0,carZ:0,bikeX:0,bikeZ:0,style:'standard'});
 useEffect(()=>{let cancelled=false;void import('./race').then(({createGame})=>{if(cancelled)return;game.current=createGame(mount.current!,setHud,(p:boolean)=>setPaused(p));setReady(true)}).catch(()=>{if(!cancelled)setError('The 3D renderer could not start. Please reload in a browser with WebGL enabled.')});return()=>{cancelled=true;game.current?.dispose()}},[]);
 const choose=async(id:MapId)=>{setReady(false);setError('');try{await game.current?.selectMap(id);setMap(id)}catch{setError('The town could not load. Please select it again to retry.')}finally{setReady(true)}};
 const menu=()=>{game.current?.menu();setStarted(false);setPaused(false)};
 const start=()=>{game.current?.start();setStarted(true);setPaused(false)};
 return <main className="game"><div ref={mount} className="viewport"/><div className="vignette"/>
 <header><a className="brand" href="#" onClick={e=>e.preventDefault()}><span className="brand-mark">/ / /</span> AFTERGLOW<span className="brand-sub">DRIFT CLUB</span></a><div className="location"><span className="live-dot"/> {maps[map].location} <span className="divider">/</span> FREE RUN</div><div className="actions">{started&&<button onClick={menu}>MAPS</button>}<button onClick={()=>{game.current?.mute(!muted);setMuted(!muted)}} aria-label={muted?'Enable audio':'Mute audio'}>{muted?'SOUND OFF':'SOUND ON'}</button>{started&&<button onClick={()=>game.current?.pause()}>{paused?'RESUME':'PAUSE'} <kbd>ESC</kbd></button>}</div></header>
 {!started&&<section className="intro map-intro"><div className="eyebrow"><span/> CHOOSE YOUR PLAYGROUND</div><h1>FIND YOUR<br/><em>SLIDE.</em></h1><RadioGroup className="map-list" value={map} disabled={!ready} onValueChange={value=>choose(value as MapId)} aria-label="Choose a map">{(Object.keys(maps) as MapId[]).map(id=><label className={'map-card '+(map===id?'selected':'')} key={id}><RadioGroupItem value={id} aria-label={maps[id].title}/><span className="map-number">{maps[id].number}</span><span className="map-copy"><b>{maps[id].title}</b><span>{maps[id].description}</span></span><span className="map-tag">{townTag(id)}</span></label>)}</RadioGroup>{isTown(map)&&<p className="town-note">Mapped streets · stylized buildings and shopfronts<br/><a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">© OpenStreetMap contributors</a> · <a href={`/maps/${map}.json`} download>Map data (ODbL)</a></p>}<div className="tuning"><span>2× SPEED</span><span>LOW GRIP</span><span>CAR + BIKE + ON FOOT</span></div><button className="drive" onClick={start} disabled={!ready}>{ready?'LET’S DRIVE':'LOADING MAP…'}<span>↗</span></button>{error&&<p role="alert">{error}</p>}</section>}
 {started&&<>{isTown(map)&&<div className="town-map"><div>{map==='wurzburg'?'WÜRZBURG':'SVITLODARSK'} <span>FOLLOW {hud.mode==='foot'?'YOU':'DRIVE'}</span></div><TownMinimap map={map} x={hud.x} z={hud.z} yaw={hud.yaw} carX={hud.carX} carZ={hud.carZ} bikeX={hud.bikeX} bikeZ={hud.bikeZ}/><a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">© OpenStreetMap contributors · ODbL</a></div>}<div className="interaction"><span className="travel-mode">{hud.mode==='foot'?'ON FOOT':hud.mode==='bike'?'BMW S1000RR':'SPORTS COUPE'}</span><span className="hint-text">{hud.hint}</span>{hud.mode==='foot'&&<small>WASD to walk · Shift to run · Drag to look</small>}</div><div className="score"><span className="eyebrow">SESSION SCORE</span><strong>{Math.floor(hud.score).toLocaleString().padStart(6,'0')}</strong><span className="score-caption">Keep it sideways. Keep it clean.</span></div><div className={'drift '+(hud.drifting?'visible':'')}><span>DRIFTING</span><strong>+{Math.floor(hud.combo)} <small>PTS</small></strong><div>{Math.round(hud.angle)}° SLIP ANGLE</div></div>{paused&&!fullMap&&<div className="pause-overlay"><h2>TAKE A BREATHER.</h2><button className="drive" onClick={()=>game.current?.pause()}>BACK TO DRIVING <span>↗</span></button><button className="change-map" onClick={menu}>CHOOSE ANOTHER MAP ↗</button><p>Esc to resume · R to reset car</p></div>}{fullMap&&isTown(map)&&<div className="full-map-open" role="dialog" aria-modal="true" aria-label={`${maps[map].title} full map`}><div className="full-map-head"><span className="eyebrow">FULL MAP <i>·</i> {maps[map].location}</span><button onClick={()=>toggleMap(false)}>CLOSE <kbd>M</kbd></button></div><TownFullMap map={map} x={hud.x} z={hud.z} yaw={hud.yaw} carX={hud.carX} carZ={hud.carZ} bikeX={hud.bikeX} bikeZ={hud.bikeZ}/><p>You (lime) · CAR / BIKE · © OpenStreetMap contributors, ODbL</p></div>}</>}
 <footer><div className="course"><div className="course-top"><span className="mini-num">{maps[map].number}</span><div><b>{maps[map].title.toUpperCase()}</b><span>{maps[map].description}</span></div></div><div className="control-row"><span><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd> {hud.mode==='foot'?'WALK':'DRIVE'}</span><span><kbd>{hud.mode==='foot'?'SHIFT':'SPACE'}</kbd> {hud.mode==='foot'?'RUN':hud.mode==='bike'?'BRAKE':'HANDBRAKE'}</span><span><kbd>M</kbd> MAP</span><span className="mode-state">MODE {hud.style==='drift'?'DRIFT':'STANDARD'}</span><span><kbd>E</kbd> {hud.mode==='foot'?'ENTER':'EXIT'}</span><span><kbd>G</kbd> {hud.style==='drift'?'STANDARD':'DRIFT'}</span><span><kbd>R</kbd> RESET</span></div></div><div className="speed"><div className="speed-top"><span>{hud.speed<3?'N':Math.min(6,1+Math.floor(hud.speed/35))}</span><b>{hud.mode==='foot'?'ON FOOT':hud.mode==='bike'?'BMW':'RWD'}</b></div><strong>{String(Math.round(hud.speed)).padStart(3,'0')}</strong><span className="units">KM/H</span><div className="rpm"><i style={{width:`${Math.min(100,12+hud.speed%35/35*88)}%`}}/></div></div></footer>
 <div className="touch-controls">{started&&<button onClick={()=>game.current?.interact()}>E</button>}{[['left','A'],['right','D'],['brake','SPACE'],['go','W']].map(([n,k])=><button key={n} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);if(paused)return;if(!started)start();game.current?.key(k,true)}} onPointerUp={()=>game.current?.key(k,false)} onPointerCancel={()=>game.current?.key(k,false)}>{n==='left'?'←':n==='right'?'→':n==='go'?'↑':'BRAKE'}</button>)}</div>
 </main>
}
