'use client';
import { useEffect, useRef, useState } from 'react';
import type { createGame, MapId, HUD } from './race';
import { TownMinimap, TownFullMap } from './town-minimap';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { getSettings, setSetting, type Settings } from './settings-store';
const MAP_KEY='afterglow.map';
const maps={coast:{title:'Coastline circuit',location:'PACIFIC COAST',description:'Sweeping corners along the coast.',number:'01'},costco:{title:'Costco parking lot',location:'COSTCO WHOLESALE',description:'Wide-open bays. Long, icy slides.',number:'02'},svitlodarsk:{title:'Svitlodarsk',location:'SVITLODARSK · UKRAINE',description:'Tree-lined streets, shops & reservoirs.',number:'03'},wurzburg:{title:'Würzburg',location:'WÜRZBURG · GERMANY',description:'Hilly streets, vineyards & the Main river.',number:'04'}};
const isTown=(map:MapId)=>map==='svitlodarsk'||map==='wurzburg';
const townTag=(id:MapId)=>id==='svitlodarsk'?'NEW':id==='costco'?'LOT':id==='wurzburg'?'HILLS':'COAST';
const vehicles=[{id:'car' as const,name:'Sports Coupe',desc:'RWD · Rear-wheel drive · Balanced drift'},{id:'bike' as const,name:'BMW S1000RR',desc:'Inline-4 · Lean physics · Narrow & fast'}];
const loadMap=():MapId=>{try{const raw=localStorage.getItem(MAP_KEY);if(raw&&raw in maps)return raw as MapId}catch{}return'coast'};

export default function Home(){
 const mount=useRef<HTMLDivElement>(null);const game=useRef<ReturnType<typeof createGame>|null>(null);
 const [ready,setReady]=useState(false),[started,setStarted]=useState(false),[paused,setPaused]=useState(false),[error,setError]=useState('');
 const [map,setMap]=useState<MapId>(loadMap);const [fullMap,setFullMap]=useState(false);const fullMapRef=useRef(fullMap),startedRef=useRef(false);
 useEffect(()=>{startedRef.current=started},[started]);
 const toggleMap=(open?:boolean)=>{if(!startedRef.current)return;const next=open??!fullMapRef.current;fullMapRef.current=next;setFullMap(next);game.current?.setMapOpen(next)};
 useEffect(()=>{const h=(e:KeyboardEvent)=>{if(e.code==='KeyM'){e.preventDefault();toggleMap()}else if(e.code==='Escape'&&fullMapRef.current){e.preventDefault();toggleMap(false)}};window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h)},[]);
 const [hud,setHud]=useState<HUD>({speed:0,score:0,combo:0,angle:0,drifting:false,x:0,z:0,yaw:0,mode:'car',hint:'',carX:0,carZ:0,bikeX:0,bikeZ:0,style:'standard'});
 useEffect(()=>{let cancelled=false;void import('./race').then(({createGame})=>{if(cancelled)return;game.current=createGame(mount.current!,setHud,(p:boolean)=>setPaused(p));setReady(true)}).catch(()=>{if(!cancelled)setError('The 3D renderer could not start. Please reload in a browser with WebGL enabled.')});return()=>{cancelled=true;game.current?.dispose()}},[]);
 const [settings,setSettingsState]=useState<Settings>(()=>getSettings());
 const chooseMap=async(id:MapId)=>{setReady(false);setError('');setMap(id);try{localStorage.setItem(MAP_KEY,id)}catch{}try{await game.current?.selectMap(id)}catch{setError('The town could not load. Please select it again to retry.')}finally{setReady(true)}};
 const menu=()=>{game.current?.menu();setStarted(false);setPaused(false);setScreen(null)};
 const startGame=async()=>{if(!ready)return;try{await game.current?.selectMap(map)}catch{setError('The map could not load. Please try again.')}game.current?.mute(settings.muted);game.current?.start();setStarted(true);setScreen(null)};
 const [splash,setSplash]=useState(true);const [screen,setScreen]=useState<'menu'|'maps'|'cars'|'settings'|null>(null);
 useEffect(()=>{const t=setTimeout(()=>setSplash(false),2200);return()=>clearTimeout(t)},[]);
 useEffect(()=>{const h=(e:KeyboardEvent)=>{if(!started&&screen&&e.code==='Escape'){e.preventDefault();setScreen(null)}};window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h)},[started,screen]);
 useEffect(()=>{if(ready)game.current?.mute(settings.muted)},[ready]);
 const setVal=<K extends keyof Settings>(k:K,v:Settings[K])=>{setSetting(k,v);setSettingsState(getSettings())};
 const toggleMute=()=>setVal('muted',!settings.muted);
 const menuBtn=(label:string,sub:string,onClick:()=>void)=><button className="menu-btn" onClick={onClick}><span className="menu-btn-label">{label}</span><span className="menu-btn-sub">{sub}</span><span className="menu-btn-arrow">↗</span></button>;

 return <main className="game"><div ref={mount} className="viewport"/><div className="vignette"/>

 {splash&&<div className="splash"><div className="splash-inner"><div className="splash-brand">AFTERGLOW</div><div className="splash-sub">DRIFT</div><div className="splash-line"/></div></div>}

 {!splash&&!started&&screen===null&&<div className="menu-bg">{isTown(map)&&<div className="menu-map-bg"><TownFullMap map={map} x={0} z={0} yaw={0} carX={0} carZ={0} bikeX={0} bikeZ={0}/></div>}<div className="menu-content"><div className="menu-left"><div className="eyebrow"><span/>AFTERGLOW DRIFT CLUB</div><h1 className="menu-title">FIND YOUR<br/><em>SLIDE.</em></h1><p className="menu-desc">Choose your playground. Choose your ride. Keep it sideways.</p></div><div className="menu-right">{menuBtn('PLAY','Selected map · '+maps[map].title,startGame)}{menuBtn('CHOOSE MAP',maps[map].title,()=>setScreen('maps'))}{menuBtn('CHOOSE CAR',vehicles.find(v=>v.id===settings.startVehicle)?.name??'Sports Coupe',()=>setScreen('cars'))}{menuBtn('SETTINGS','Sound · Drive style',()=>setScreen('settings'))}</div></div></div>}

 {!splash&&!started&&screen==='maps'&&<div className="overlay"><div className="overlay-head"><span className="eyebrow">CHOOSE MAP</span><button className="overlay-close" onClick={()=>setScreen(null)}>CLOSE <kbd>ESC</kbd></button></div><div className="overlay-body"><RadioGroup className="map-list" value={map} onValueChange={v=>chooseMap(v as MapId)} aria-label="Choose a map">{(Object.keys(maps) as MapId[]).map(id=><label className={'map-card '+(map===id?'selected':'')} key={id}><RadioGroupItem value={id} aria-label={maps[id].title}/><span className="map-number">{maps[id].number}</span><span className="map-copy"><b>{maps[id].title}</b><span>{maps[id].description}</span></span><span className="map-tag">{townTag(id)}</span></label>)}</RadioGroup>{isTown(map)&&<p className="town-note">Mapped streets · stylized buildings and shopfronts<br/><a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">© OpenStreetMap contributors</a> · <a href={`/maps/${map}.json`} download>Map data (ODbL)</a></p>}<button className="menu-create-map" disabled>CREATE YOUR OWN MAP <span>Coming soon</span></button></div></div>}

 {!splash&&!started&&screen==='cars'&&<div className="overlay"><div className="overlay-head"><span className="eyebrow">CHOOSE CAR</span><button className="overlay-close" onClick={()=>setScreen(null)}>CLOSE <kbd>ESC</kbd></button></div><div className="overlay-body"><div className="car-list">{vehicles.map(v=><button key={v.id} className={'car-card '+(settings.startVehicle===v.id?'selected':'')} onClick={()=>setVal('startVehicle',v.id)}><div className="car-icon">{v.id==='car'?'🏎️':'🏍️'}</div><div className="car-info"><b>{v.name}</b><span>{v.desc}</span></div>{settings.startVehicle===v.id&&<div className="car-check">✓</div>}</button>)}</div></div></div>}

 {!splash&&!started&&screen==='settings'&&<div className="overlay"><div className="overlay-head"><span className="eyebrow">SETTINGS</span><button className="overlay-close" onClick={()=>setScreen(null)}>CLOSE <kbd>ESC</kbd></button></div><div className="overlay-body"><div className="settings-grid"><div className="setting-row"><span className="setting-label">Sound</span><span className="setting-val">{settings.muted?'OFF':'ON'}</span><button className="setting-toggle" onClick={toggleMute}>{settings.muted?'TURN ON':'TURN OFF'}</button></div><div className="setting-row"><span className="setting-label">Drive style</span><span className="setting-val">{settings.driveStyle==='drift'?'DRIFT':'STANDARD'}</span><div className="setting-btns"><button className={'setting-btn '+(settings.driveStyle==='standard'?'active':'')} onClick={()=>setVal('driveStyle','standard')}>STANDARD</button><button className={'setting-btn '+(settings.driveStyle==='drift'?'active':'')} onClick={()=>setVal('driveStyle','drift')}>DRIFT</button></div></div><div className="setting-row"><span className="setting-label">Vehicle</span><span className="setting-val">{vehicles.find(v=>v.id===settings.startVehicle)?.name}</span><button className="setting-link" onClick={()=>setScreen('cars')}>Change →</button></div><div className="setting-row"><span className="setting-label">Map</span><span className="setting-val">{maps[map].title}</span><button className="setting-link" onClick={()=>setScreen('maps')}>Change →</button></div></div></div></div>}

 <header><a className="brand" href="#" onClick={e=>e.preventDefault()}><span className="brand-mark">/ / /</span> AFTERGLOW<span className="brand-sub">DRIFT CLUB</span></a><div className="location"><span className="live-dot"/> {maps[map].location} <span className="divider">/</span> FREE RUN</div><div className="actions">{started&&<button onClick={menu}>MAPS</button>}<button onClick={toggleMute} aria-label={settings.muted?'Enable audio':'Mute audio'}>{settings.muted?'SOUND OFF':'SOUND ON'}</button>{started&&<button onClick={()=>game.current?.pause()}>{paused?'RESUME':'PAUSE'} <kbd>ESC</kbd></button>}</div></header>

 {started&&<>{isTown(map)&&<div className="town-map"><div>{map==='wurzburg'?'WÜRZBURG':'SVITLODARSK'} <span>FOLLOW {hud.mode==='foot'?'YOU':'DRIVE'}</span></div><TownMinimap map={map} x={hud.x} z={hud.z} yaw={hud.yaw} carX={hud.carX} carZ={hud.carZ} bikeX={hud.bikeX} bikeZ={hud.bikeZ}/><a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">© OpenStreetMap contributors · ODbL</a></div>}<div className="interaction"><span className="travel-mode">{hud.mode==='foot'?'ON FOOT':hud.mode==='bike'?'BMW S1000RR':'SPORTS COUPE'}</span><span className="hint-text">{hud.hint}</span>{hud.mode==='foot'&&<small>WASD to walk · Shift to run · Drag to look</small>}</div><div className="score"><span className="eyebrow">SESSION SCORE</span><strong>{Math.floor(hud.score).toLocaleString().padStart(6,'0')}</strong><span className="score-caption">Keep it sideways. Keep it clean.</span></div><div className={'drift '+(hud.drifting?'visible':'')}><span>DRIFTING</span><strong>+{Math.floor(hud.combo)} <small>PTS</small></strong><div>{Math.round(hud.angle)}° SLIP ANGLE</div></div>{paused&&!fullMap&&<div className="pause-overlay"><h2>TAKE A BREATHER.</h2><button className="drive" onClick={()=>game.current?.pause()}>BACK TO DRIVING <span>↗</span></button><button className="change-map" onClick={menu}>CHOOSE ANOTHER MAP ↗</button><p>Esc to resume · R to reset car</p></div>}{fullMap&&isTown(map)&&<div className="full-map-open" role="dialog" aria-modal="true" aria-label={`${maps[map].title} full map`}><div className="full-map-head"><span className="eyebrow">FULL MAP <i>·</i> {maps[map].location}</span><button onClick={()=>toggleMap(false)}>CLOSE <kbd>M</kbd></button></div><TownFullMap map={map} x={hud.x} z={hud.z} yaw={hud.yaw} carX={hud.carX} carZ={hud.carZ} bikeX={hud.bikeX} bikeZ={hud.bikeZ}/><p>You (lime) · CAR / BIKE · © OpenStreetMap contributors, ODbL</p></div>}</>}

 <footer><div className="course"><div className="course-top"><span className="mini-num">{maps[map].number}</span><div><b>{maps[map].title.toUpperCase()}</b><span>{maps[map].description}</span></div></div><div className="control-row"><span><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd> {hud.mode==='foot'?'WALK':'DRIVE'}</span><span><kbd>{hud.mode==='foot'?'SHIFT':'SPACE'}</kbd> {hud.mode==='foot'?'RUN':hud.mode==='bike'?'BRAKE':'HANDBRAKE'}</span><span><kbd>M</kbd> MAP</span><span className="mode-state">MODE {hud.style==='drift'?'DRIFT':'STANDARD'}</span><span><kbd>E</kbd> {hud.mode==='foot'?'ENTER':'EXIT'}</span><span><kbd>G</kbd> {hud.style==='drift'?'STANDARD':'DRIFT'}</span><span><kbd>R</kbd> RESET</span></div></div><div className="speed"><div className="speed-top"><span>{hud.speed<3?'N':Math.min(6,1+Math.floor(hud.speed/35))}</span><b>{hud.mode==='foot'?'ON FOOT':hud.mode==='bike'?'BMW':'RWD'}</b></div><strong>{String(Math.round(hud.speed)).padStart(3,'0')}</strong><span className="units">KM/H</span><div className="rpm"><i style={{width:`${Math.min(100,12+hud.speed%35/35*88)}%`}}/></div></div></footer>
 <div className="touch-controls">{started&&<button onClick={()=>game.current?.interact()}>E</button>}{[['left','A'],['right','D'],['brake','SPACE'],['go','W']].map(([n,k])=><button key={n} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);if(paused)return;if(!started)startGame();game.current?.key(k,true)}} onPointerUp={()=>game.current?.key(k,false)} onPointerCancel={()=>game.current?.key(k,false)}>{n==='left'?'←':n==='right'?'→':n==='go'?'↑':'BRAKE'}</button>)}</div>
 </main>
}
