import * as T from 'three';
import {createCharacter,createMotorbike} from './actors';
import {createEffects,grainTexture} from './visuals';
import {nearestVehicle,exitCandidates,type TravelMode} from './vehicle-state';
import { createParking, parkingCollision } from './parking';
import {createTown} from './town';
import {loadTownData} from './town-data';
export type MapId='coast'|'costco'|'svitlodarsk';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';

export type HUD={speed:number,score:number,combo:number,angle:number,drifting:boolean,x:number,z:number,yaw:number,mode:TravelMode,hint:string,carX:number,carZ:number,bikeX:number,bikeZ:number};
export function createGame(host:HTMLElement,onHUD:(h:HUD)=>void,onPause:(p:boolean)=>void){
 const scene=new T.Scene();scene.background=new T.Color('#80959e');scene.fog=new T.FogExp2('#9ba6a8',.0025);
 const renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;host.appendChild(renderer.domElement);
 const camera=new T.PerspectiveCamera(48,innerWidth/innerHeight,.1,8000);
 const pmrem=new T.PMREMGenerator(renderer),room=new RoomEnvironment();const env=pmrem.fromScene(room,.04);scene.environment=env.texture;room.dispose();pmrem.dispose();
 scene.add(new T.HemisphereLight('#afdaff','#524635',1.6));const sun=new T.DirectionalLight('#ffe0a1',3.8);sun.position.set(-90,80,-130);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-65,right:65,top:65,bottom:-65,near:1,far:350});sun.shadow.bias=-.0005;scene.add(sun,sun.target);
 const effects=createEffects(renderer,scene,camera);
 const sky=new T.Mesh(new T.SphereGeometry(1300,40,24),new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms:{},vertexShader:'varying vec3 v;void main(){v=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec3 v;float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.54);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+vec2(1,1)),f.x),f.y);}void main(){vec3 n=normalize(v);float h=n.y;vec3 c=mix(vec3(.98,.65,.39),vec3(.29,.48,.64),smoothstep(-.08,.6,h));vec2 p=n.xz/(max(.1,h)+.2)*3.;float f=noise(p)*.6+noise(p*2.1)*.3+noise(p*4.3)*.1;float clouds=smoothstep(.48,.76,f)*smoothstep(.02,.3,h);c=mix(c,vec3(.86,.86,.81),clouds*.75);gl_FragColor=vec4(c,1.);}'}));scene.add(sky);
 const sunDisc=new T.Mesh(new T.SphereGeometry(23,32,16),new T.MeshBasicMaterial({color:'#ffe0a1',fog:false}));sunDisc.position.set(-440,105,-780);scene.add(sunDisc);
 const mat=(color:string,roughness=.8,metalness=0)=>new T.MeshStandardMaterial({color,roughness,metalness});
 const roadGrain=grainTexture();
 const asphalt=mat('#363e41',.75),sand=mat('#8c846b'),white=mat('#e3d9c2'),red=mat('#ba5c45'),dark=mat('#0b141a',.4),metal=mat('#a5b3b9',.25,.85);
 asphalt.bumpMap=roadGrain;asphalt.bumpScale=.035;
 let worldRoot:T.Object3D=scene;
 function mesh(g:T.BufferGeometry,m:T.Material,x=0,y=0,z=0,parent:T.Object3D=worldRoot){const a=new T.Mesh(g,m);a.position.set(x,y,z);a.castShadow=true;a.receiveShadow=true;parent.add(a);return a}
 const coast=new T.Group();scene.add(coast);worldRoot=coast;
 const ground=mesh(new T.PlaneGeometry(1000,1250),sand,325,-.13,0);ground.rotation.x=-Math.PI/2;
 const sea=mesh(new T.PlaneGeometry(1600,1500,1,1),new T.MeshStandardMaterial({color:'#46767e',metalness:.65,roughness:.27}),-810,-1.2,0);sea.rotation.x=-Math.PI/2;
 // The circuit is a closed flowing spline with room to drift on each side.
 const points=[[-92,8],[-75,-78],[-12,-121],[78,-101],[122,-36],[90,28],[113,106],[30,140],[-43,109],[-54,59]].map(([x,z])=>new T.Vector3(x,0,z));
 const curve=new T.CatmullRomCurve3(points,true,'catmullrom',.5);const samples=curve.getSpacedPoints(400);const roadHalf=12.5;
 function ribbon(a:number,b:number,y:number,m:T.Material){const pos:number[]=[],idx:number[]=[];for(let i=0;i<=400;i++){const p=samples[i];const t=curve.getTangentAt(i/400);const n=new T.Vector3(-t.z,0,t.x);for(const off of [a,b])pos.push(p.x+n.x*off,y,p.z+n.z*off);if(i<400){let j=i*2;idx.push(j,j+2,j+1,j+1,j+2,j+3)}}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(pos,3));for(let k=0;k<idx.length;k+=3){[idx[k+1],idx[k+2]]=[idx[k+2],idx[k+1]]}g.setIndex(idx);g.computeVertexNormals();const o=mesh(g,m);o.castShadow=false;return o}
 ribbon(-roadHalf,roadHalf,0,asphalt);ribbon(-13.5,-12.4,.01,white);ribbon(12.4,13.5,.01,white);
 for(let i=0;i<400;i+=2){const p=samples[i],t=curve.getTangentAt(i/400);const n=new T.Vector3(-t.z,0,t.x);for(const side of [-1,1]){const curb=mesh(new T.BoxGeometry(.9,.08,2.7),i%4===0?red:white,p.x+n.x*13*side,.02,p.z+n.z*13*side);curb.rotation.y=Math.atan2(t.x,t.z)}}
 for(let i=0;i<400;i+=5){const p=samples[i],t=curve.getTangentAt(i/400);const a=mesh(new T.PlaneGeometry(.15,2.5),white,p.x,.016,p.z);a.rotation.set(-Math.PI/2,0,-Math.atan2(t.x,t.z));}
 // Scenic mountain ridges, pines, floodlights and trackside safety barriers.
 let seed=318;function random(){seed=(seed*16807)%2147483647;return(seed-1)/2147483646}
 for(let i=0;i<42;i++){const x=190+random()*400,z=-450+random()*900,h=35+random()*160;const mountain=mesh(new T.ConeGeometry(45+random()*90,h,5),mat(i%2?'#657678':'#71817e'),x,h*.5-3,z);mountain.rotation.y=random()*6;}
 function tree(x:number,z:number,s:number){mesh(new T.CylinderGeometry(.2*s,.35*s,5*s,6),mat('#665744'),x,2*s,z);for(let j=0;j<3;j++)mesh(new T.ConeGeometry((2.5-j*.5)*s,4*s,7),mat(j%2?'#3c5750':'#425a51'),x,(4+j*1.4)*s,z)}
 for(let i=0;i<120;i++){const x=-135+random()*360,z=-230+random()*460;const d=Math.min(...samples.filter((_,j)=>j%4===0).map(p=>Math.hypot(p.x-x,p.z-z)));if(d>23)tree(x,z,.8+random()*1.2)}
 for(let i=0;i<400;i+=16){const p=samples[i],t=curve.getTangentAt(i/400),n=new T.Vector3(-t.z,0,t.x);for(const side of [-1,1]){const x=p.x+n.x*17*side,z=p.z+n.z*17*side;const bar=mesh(new T.BoxGeometry(.3,.65,9),metal,x,.9,z);bar.rotation.y=Math.atan2(t.x,t.z);mesh(new T.CylinderGeometry(.08,.08,1.2,6),metal,x,.5,z)}if(i%32===0){const x=p.x+n.x*20,z=p.z+n.z*20;mesh(new T.CylinderGeometry(.12,.2,9,8),dark,x,4.4,z);const lamp=mesh(new T.BoxGeometry(2,.13,.8),new T.MeshStandardMaterial({color:'#fff4cb',emissive:'#ffd38c',emissiveIntensity:3}),x,9,z);lamp.rotation.z=.12}}
 const parking=createParking();scene.add(parking.group);parking.group.visible=false;worldRoot=scene;let mapId:MapId='coast';let town:ReturnType<typeof createTown>|null=null;
 // Sculpted coupe: shaped cross sections, separate glass canopy, fenders and aero.
 const car=new T.Group();scene.add(car);const paint=new T.MeshPhysicalMaterial({color:'#cbdcbd',metalness:.72,roughness:.24,clearcoat:1,clearcoatRoughness:.12});const glass=new T.MeshPhysicalMaterial({color:'#122a35',metalness:.7,roughness:.14,clearcoat:1});
 function loft(rows:number[][],material:T.Material){const v:number[]=[],ix:number[]=[];for(const [z,w,lower,shoulder,top]of rows){v.push(-w,lower,z,-w,shoulder,z,-w*.78,top,z,w*.78,top,z,w,shoulder,z,w,lower,z)}for(let j=0;j<rows.length-1;j++)for(let k=0;k<6;k++){const a=j*6+k,b=j*6+(k+1)%6;ix.push(a,b,a+6,b,b+6,a+6)}ix.push(0,2,1,0,3,2,0,5,3,3,5,4);const a=(rows.length-1)*6;ix.push(a,a+1,a+2,a,a+2,a+3,a,a+3,a+5,a+3,a+4,a+5);const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(v,3));for(let k=0;k<ix.length;k+=3){[ix[k+1],ix[k+2]]=[ix[k+2],ix[k+1]]}g.setIndex(ix);g.computeVertexNormals();return mesh(g,material,0,0,0,car)}
 loft([[-2.45,.81,.32,.52,.58],[-2.08,1,.3,.7,.76],[-1.38,1.01,.32,.85,.88],[-.65,.95,.34,.78,.85],[.7,.98,.34,.83,.9],[1.55,1.06,.32,.88,.94],[2.18,1.01,.34,.74,.8],[2.4,.88,.4,.68,.71]],paint);
 loft([[-.97,.83,.81,.84,.87],[-.36,.73,.85,1.34,1.42],[.65,.76,.85,1.38,1.47],[1.37,.87,.83,.9,.94]],glass);
 loft([[-.32,.75,1.37,1.4,1.44],[.68,.77,1.41,1.44,1.48]],paint);
 const wheels:T.Group[]=[];for(const x of [-1.02,1.02])for(const z of [-1.43,1.48]){const pivot=new T.Group();pivot.position.set(x,.45,z);car.add(pivot);wheels.push(pivot);const tire=mesh(new T.CylinderGeometry(.43,.43,.31,32),mat('#13171a',.96),0,0,0,pivot);tire.rotation.z=Math.PI/2;const rim=mesh(new T.CylinderGeometry(.3,.3,.325,24),mat('#323d43',.28,.9),0,0,0,pivot);rim.rotation.z=Math.PI/2;for(let k=0;k<5;k++){const spoke=mesh(new T.BoxGeometry(.34,.055,.54),metal,0,0,0,pivot);spoke.rotation.x=k*Math.PI/5}const hub=mesh(new T.CylinderGeometry(.09,.09,.35,12),metal,0,0,0,pivot);hub.rotation.z=Math.PI/2;}
 for(const side of [-1,1]){const skirt=mesh(new T.BoxGeometry(.1,.13,2.2),dark,side*1.01,.34,0,car);mesh(new T.BoxGeometry(.23,.11,.34),paint,side*1.0,1.02,-.54,car);mesh(new T.BoxGeometry(.025,.035,.24),metal,side*.966,.83,.45,car);for(const z of [-1.43,1.48]){const arch=mesh(new T.TorusGeometry(.47,.065,8,24,Math.PI),paint,side*1.015,.45,z,car);arch.rotation.y=Math.PI/2}}
 mesh(new T.BoxGeometry(1.8,.09,.4),dark,0,.31,-2.28,car);mesh(new T.BoxGeometry(1.5,.21,.04),dark,0,.46,-2.445,car);
 const headMat=new T.MeshStandardMaterial({color:'#e4faff',emissive:'#bceaff',emissiveIntensity:4});const tailMat=new T.MeshStandardMaterial({color:'#ff3730',emissive:'#ff1609',emissiveIntensity:3});
 for(const x of [-.64,.64]){const h=mesh(new T.BoxGeometry(.44,.065,.05),headMat,x,.62,-2.33,car);h.rotation.y=x*.12;mesh(new T.BoxGeometry(.5,.07,.04),tailMat,x,.68,2.35,car);const exhaust=mesh(new T.CylinderGeometry(.095,.095,.2,14),metal,x,.37,2.39,car);exhaust.rotation.x=Math.PI/2;}
 mesh(new T.BoxGeometry(1.88,.07,.36),dark,0,1.02,2.05,car);for(const x of [-.6,.6])mesh(new T.BoxGeometry(.07,.24,.1),dark,x,.89,2.05,car);
 const plate=mesh(new T.BoxGeometry(.48,.12,.02),white,0,.52,2.405,car);
 // Reusable smoke sprites and skid segments keep long sessions lightweight.
 const cv=document.createElement('canvas');cv.width=cv.height=64;const ctx=cv.getContext('2d')!;const grad=ctx.createRadialGradient(32,32,0,32,32,32);grad.addColorStop(0,'rgba(220,226,221,.5)');grad.addColorStop(1,'rgba(220,226,221,0)');ctx.fillStyle=grad;ctx.fillRect(0,0,64,64);const smokeTex=new T.CanvasTexture(cv);
 const smoke=Array.from({length:100},()=>{const s=new T.Sprite(new T.SpriteMaterial({map:smokeTex,transparent:true,depthWrite:false,opacity:0}));scene.add(s);return{s,life:0}});let smokeIndex=0;
 const skidMat=new T.MeshBasicMaterial({color:'#11191c',transparent:true,opacity:.45,depthWrite:false});const skids=Array.from({length:500},()=>{const s=mesh(new T.PlaneGeometry(.24,.7),skidMat);s.rotation.x=-Math.PI/2;s.visible=false;s.castShadow=false;return s});let skidIndex=0;
 const motorbike=createMotorbike();scene.add(motorbike.group);const character=createCharacter();scene.add(character.group);
 for(const [vehicle,intensity] of [[car,12],[motorbike.group,8]] as [T.Group,number][]){const light=new T.SpotLight('#ffe5b0',intensity,45,.45,.7,1);light.position.set(0,1,-1);light.target.position.set(0,.05,-25);vehicle.add(light,light.target);}
 const keys:Record<string,boolean>={};let active=false,paused=false,disposed=false,muted=false,yaw=0,vx=0,vz=0,steer=0,score=0,combo=0,driftGrace=0,frame=0,clock=0,raf=0,accum=0;
 let mode:TravelMode='car',driven=car,cameraOrbit=0,walkPhase=0,notice='',noticeUntil=0,dragging=false,lastPointerX=0;
 let audio:AudioContext|null=null,osc:OscillatorNode|null=null,gain:GainNode|null=null;
 const focus=()=>mode==='foot'?character.group:driven;
 const pose=(v:T.Group)=>({x:v.position.x,z:v.position.z,yaw:v.rotation.y});
 function ensureAudio(){if(!audio){audio=new AudioContext();osc=audio.createOscillator();osc.type='sawtooth';gain=audio.createGain();gain.gain.value=0;const filter=audio.createBiquadFilter();filter.type='lowpass';filter.frequency.value=240;osc.connect(filter).connect(gain).connect(audio.destination);osc.start()}void audio.resume()}
 function hint(){if(clock<noticeUntil)return notice;if(mode!=='foot')return 'E · Get out of '+(mode==='car'?'sports car':'motorbike');const nearest=nearestVehicle({x:character.group.position.x,z:character.group.position.z},pose(car),pose(motorbike.group));if(nearest)return 'E · '+(nearest==='car'?'Enter sports car':'Ride GPZ motorbike');return 'Walk to a vehicle · R to regroup'}
 function emit(drifting=false,angle=0){const f=focus();onHUD({speed:Math.hypot(vx,vz)*3.6,score,combo,angle,drifting,x:f.position.x,z:f.position.z,yaw,mode,hint:hint(),carX:car.position.x,carZ:car.position.z,bikeX:motorbike.group.position.x,bikeZ:motorbike.group.position.z})}
 function groundCollision(x:number,z:number,dx:number,dz:number,previous:[number,number],radius:number){if(mapId==='svitlodarsk'&&town)return town.collide(x,z,dx,dz,previous,radius);if(mapId==='costco')return parkingCollision(x,z,dx,dz,parking.obstacles,radius);let nearest=0,distance=Infinity;for(let i=0;i<400;i++){const d=(x-samples[i].x)**2+(z-samples[i].z)**2;if(d<distance){distance=d;nearest=i}}const off=Math.sqrt(distance);let hit=false;if(off>16){const p=samples[nearest],nx=(x-p.x)/off,nz=(z-p.z)/off;x=p.x+nx*16;z=p.z+nz*16;const out=dx*nx+dz*nz;if(out>0){dx-=nx*out*1.4;dz-=nz*out*1.4}hit=true}return{x,z,vx:dx,vz:dz,hit}}
 function applyCharacter(moving=0){if(mode==='foot'){character.group.scale.setScalar(1);character.group.rotation.set(0,yaw,0);character.pose('foot',walkPhase,moving)}else{const local=mode==='car'?new T.Vector3(.38,-.02,.13):new T.Vector3(0,.17,.28);local.applyAxisAngle(new T.Vector3(0,1,0),yaw);character.group.position.copy(driven.position).add(local);character.group.rotation.set(0,yaw,mode==='bike'?driven.rotation.z:0);character.group.scale.setScalar(mode==='car'?.76:1);character.pose(mode,0,0)}}
 function reset(){const p=mapId==='svitlodarsk'&&town?new T.Vector3(town.data.spawn.x,0,town.data.spawn.z):mapId==='costco'?new T.Vector3(0,0,75):curve.getPointAt(.03),t=mapId==='svitlodarsk'&&town?new T.Vector3(-Math.sin(town.data.spawn.yaw),0,-Math.cos(town.data.spawn.yaw)):mapId==='costco'?new T.Vector3(0,0,-1):curve.getTangentAt(.03);car.position.set(p.x,0,p.z);yaw=Math.atan2(-t.x,-t.z);car.rotation.set(0,yaw,0);const bikeOffset=new T.Vector3(3.5,0,-4).applyAxisAngle(new T.Vector3(0,1,0),yaw);motorbike.group.position.copy(car.position).add(bikeOffset);motorbike.group.rotation.set(0,yaw,-.09);mode='car';driven=car;cameraOrbit=yaw;vx=vz=steer=combo=driftGrace=accum=0;noticeUntil=0;for(const k in keys)keys[k]=false;applyCharacter();emit();updateCamera(1)}
 function updateCamera(dt:number){const f=focus();const heading=mode==='foot'?cameraOrbit:yaw,forward=new T.Vector3(-Math.sin(heading),0,-Math.cos(heading));let target:T.Vector3;if(!active){target=f.position.clone().add(new T.Vector3(-9,4.7,9));camera.position.lerp(target,Math.min(1,dt*2));camera.lookAt(f.position.clone().add(new T.Vector3(-3.2,.7,0)))}else{target=f.position.clone().addScaledVector(forward,mode==='foot'?-4.7:mode==='bike'?-6.5:-8.8-Math.min(3,Math.hypot(vx,vz)*.07));target.y=mode==='foot'?2.9:mode==='bike'?3.2:4.5;camera.position.lerp(target,1-Math.exp(-dt*5));camera.lookAt(f.position.clone().addScaledVector(forward,mode==='foot'?1:4).add(new T.Vector3(0,mode==='foot'?1.2:.9,0)))}const fov=mode==='foot'?55:48+Math.min(9,Math.hypot(vx,vz)*.08);camera.fov+=(fov-camera.fov)*Math.min(1,dt*3);camera.updateProjectionMatrix()}
 function avoidVehicle(x:number,z:number,v:T.Group,width:number,length:number){const local=new T.Vector3(x-v.position.x,0,z-v.position.z).applyAxisAngle(new T.Vector3(0,1,0),-v.rotation.y);if(Math.abs(local.x)<width&&Math.abs(local.z)<length){if(width-Math.abs(local.x)<length-Math.abs(local.z))local.x=Math.sign(local.x||1)*width;else local.z=Math.sign(local.z||1)*length;local.applyAxisAngle(new T.Vector3(0,1,0),v.rotation.y).add(v.position);return[local.x,local.z] as [number,number]}return[x,z] as [number,number]}
 function walking(dt:number){const forward=(keys.W?1:0)-(keys.S?1:0),strafe=(keys.D?1:0)-(keys.A?1:0);const length=Math.hypot(forward,strafe),speed=keys.Shift?6.4:3.1;vx=length?(-Math.sin(cameraOrbit)*forward+Math.cos(cameraOrbit)*strafe)*speed/length:0;vz=length?(-Math.cos(cameraOrbit)*forward-Math.sin(cameraOrbit)*strafe)*speed/length:0;const f=character.group,previous:[number,number]=[f.position.x,f.position.z];const c=groundCollision(f.position.x+vx*dt,f.position.z+vz*dt,vx,vz,previous,.4);let pos=avoidVehicle(c.x,c.z,car,1.45,2.8);pos=avoidVehicle(pos[0],pos[1],motorbike.group,.8,1.7);f.position.set(pos[0],0,pos[1]);if(length){const desired=Math.atan2(-vx,-vz);yaw+=Math.atan2(Math.sin(desired-yaw),Math.cos(desired-yaw))*Math.min(1,dt*12)}walkPhase+=dt*(keys.Shift?12:8)*Math.min(length,1);applyCharacter(Math.min(length,1));if(frame%6===0)emit();if(gain&&audio)gain.gain.setTargetAtTime(0,audio.currentTime,.1)}
 function interact(){if(!active||paused)return;if(mode==='foot'){const nearest=nearestVehicle({x:character.group.position.x,z:character.group.position.z},pose(car),pose(motorbike.group));if(!nearest){notice='Get closer to a vehicle';noticeUntil=clock+2000;emit();return}mode=nearest;driven=mode==='car'?car:motorbike.group;yaw=driven.rotation.y;vx=vz=steer=0;applyCharacter();emit();return}if(Math.hypot(vx,vz)>5){notice='Slow down to exit';noticeUntil=clock+1800;emit();return}const candidates=exitCandidates(pose(driven));let safe:[number,number]|null=null;for(const p of candidates){const c=groundCollision(p[0],p[1],0,0,[driven.position.x,driven.position.z],.4);if(!c.hit){safe=p;break}}if(!safe){notice='Move to an open spot to exit';noticeUntil=clock+2000;emit();return}if(mode==='bike')motorbike.group.rotation.z=-.09;mode='foot';vx=vz=steer=combo=0;cameraOrbit=yaw;character.group.position.set(safe[0],0,safe[1]);for(const k in keys)keys[k]=false;applyCharacter();emit()}
 function physics(dt:number){if(mode==='foot'){walking(dt);return}const speed=Math.hypot(vx,vz),fx=-Math.sin(yaw),fz=-Math.cos(yaw),rx=Math.cos(yaw),rz=-Math.sin(yaw);let longitudinal=vx*fx+vz*fz,lateral=vx*rx+vz*rz;const throttle=(keys.W?1:0)-(keys.S?1:0);const turn=(keys.A?1:0)-(keys.D?1:0),brake=!!keys.SPACE,biking=mode==='bike';
 steer+=(turn-steer)*Math.min(1,dt*9);longitudinal+=throttle*(throttle*longitudinal<0?48:biking?29:34)*dt;longitudinal*=Math.exp(-(brake?(biking?1.2:.48):.16+speed*.0008)*dt);longitudinal=T.MathUtils.clamp(longitudinal,biking?-6:-24,biking?72:114);
 const slip=brake&&speed>5;const grip=biking?(brake?2:6):(slip?.22:Math.abs(steer)>.2&&speed>12?.75:1.65);lateral*=Math.exp(-grip*dt);
 yaw+=steer*Math.min(Math.abs(longitudinal)/8,1)*(.95+Math.min(speed,65)*.004)*(longitudinal<0?-1:1)*dt*(slip&&!biking?1.3:1);
 const previous:[number,number]=[driven.position.x,driven.position.z];vx=fx*longitudinal+rx*lateral;vz=fz*longitudinal+rz*lateral;const c=groundCollision(driven.position.x+vx*dt,driven.position.z+vz*dt,vx,vz,previous,biking?.85:2.2);driven.position.x=c.x;driven.position.z=c.z;vx=c.vx;vz=c.vz;if(c.hit)combo=0;
 const other=biking?car:motorbike.group;const separation=driven.position.distanceTo(other.position);if(separation<(biking?2.2:2.1)&&separation>.001){const n=driven.position.clone().sub(other.position).normalize();driven.position.copy(other.position).addScaledVector(n,2.25);const into=vx*n.x+vz*n.z;if(into<0){vx-=1.2*into*n.x;vz-=1.2*into*n.z}combo=0}
 const slipAngle=Math.abs(Math.atan2(lateral,Math.abs(longitudinal)))*180/Math.PI;const drifting=!biking&&!c.hit&&speed>7&&(slipAngle>9||slip&&Math.abs(steer)>.2);if(drifting){const points=dt*speed*(1+Math.min(slipAngle,60)/15);score+=points;combo+=points;driftGrace=1}else{driftGrace-=dt;if(driftGrace<=0)combo=0}
 driven.rotation.set(0,yaw,biking?steer*Math.min(.42,speed*.014):-steer*Math.min(.035,speed*.001));if(!biking){tailMat.emissiveIntensity=brake||keys.S?7:2;wheels.forEach((w,i)=>{w.rotation.y=i%2===0?-steer*.4:0;w.children.forEach(c=>{if(c instanceof T.Mesh&&c.geometry.type==='BoxGeometry')c.rotation.x+=longitudinal*dt/.43})})}else{motorbike.wheels.forEach(w=>w.rotation.x-=longitudinal*dt/.43);(motorbike.tailLight.material as T.MeshStandardMaterial).emissiveIntensity=brake?5:2}applyCharacter();
 if(drifting&&frame%3===0){for(const side of [-1,1]){const pos=new T.Vector3(side,.1,1.5).applyAxisAngle(new T.Vector3(0,1,0),yaw).add(driven.position);const puff=smoke[smokeIndex++%smoke.length];puff.s.position.copy(pos);puff.life=1;puff.s.scale.setScalar(.6);const skid=skids[skidIndex++%skids.length];skid.visible=true;skid.position.set(pos.x,.027,pos.z);skid.rotation.z=-Math.atan2(vx,vz)}}
 if(frame%6===0)emit(drifting,slipAngle);if(osc&&gain&&audio){osc.frequency.setTargetAtTime((biking?52:32)+speed*(biking?3.1:2.4)+(keys.W?20:0),audio.currentTime,.08);gain.gain.setTargetAtTime(muted?0:.025+(keys.W?.025:0),audio.currentTime,.1)}
 }
 function loop(now:number){if(disposed)return;const dt=Math.min((now-clock)/1000||.016,.05);clock=now;frame++;if(active&&!paused){accum+=dt;while(accum>=1/120){physics(1/120);accum-=1/120}}for(const p of smoke){if(p.life>0&&!paused){p.life-=dt*.55;p.s.position.y+=dt*.6;p.s.scale.addScalar(dt*1.7);p.s.material.opacity=Math.max(0,p.life*.45)}}updateCamera(dt);const f=focus();sun.position.set(f.position.x-90,80,f.position.z-130);sun.target.position.copy(f.position);sky.position.copy(camera.position);sunDisc.position.copy(camera.position).add(new T.Vector3(-440,105,-780));town?.update(clock*.001);effects.render();raf=requestAnimationFrame(loop)}
 function pause(){if(!active)return;paused=!paused;dragging=false;for(const k in keys)keys[k]=false;onPause(paused);if(gain&&audio)gain.gain.setTargetAtTime(0,audio.currentTime,.03)}
 function key(k:string,down:boolean){if(k==='E'){if(down)interact();return}keys[k]=down}
 function menu(){active=false;paused=false;dragging=false;for(const k in keys)keys[k]=false;onPause(false);if(gain&&audio)gain.gain.setTargetAtTime(0,audio.currentTime,.03)}
 async function selectMap(id:MapId){if(id!=='coast'&&id!=='costco'&&id!=='svitlodarsk')throw new Error('Unknown map');if(id==='svitlodarsk'&&!town){const data=await loadTownData();if(disposed)return;town=createTown(data);scene.add(town.group)}mapId=id;coast.visible=id==='coast';parking.group.visible=id==='costco';if(town)town.group.visible=id==='svitlodarsk';(scene.fog as T.FogExp2).density=id==='svitlodarsk'?.0008:.0025;score=0;skids.forEach(s=>s.visible=false);smoke.forEach(p=>{p.life=0;p.s.material.opacity=0});reset()}
 const normalize=(code:string)=>code==='Space'?'SPACE':code.startsWith('Shift')?'Shift':code.replace('Key','').replace('ArrowUp','W').replace('ArrowDown','S').replace('ArrowLeft','A').replace('ArrowRight','D');
 function down(e:KeyboardEvent){if(!active)return;const k=normalize(e.code);if(['W','A','S','D','SPACE','Escape','R','E','Shift'].includes(k)){e.preventDefault();if(k==='Escape'&&!e.repeat)pause();else if(k==='R'&&!e.repeat)reset();else if(k==='E'&&!e.repeat)interact();else keys[k]=true}}
 function up(e:KeyboardEvent){keys[normalize(e.code)]=false}
 function blur(){if(active&&!paused)pause();for(const k in keys)keys[k]=false}
 function pointerDown(e:PointerEvent){if(mode==='foot'&&active&&!paused){dragging=true;lastPointerX=e.clientX;renderer.domElement.setPointerCapture(e.pointerId)}}
 function pointerMove(e:PointerEvent){if(dragging){cameraOrbit-=(e.clientX-lastPointerX)*.006;lastPointerX=e.clientX}}
 function pointerUp(){dragging=false}
 function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);effects.resize()}
 const lifecycle=new AbortController();const options={signal:lifecycle.signal};
 const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(context?.registerTool){try{Promise.resolve(context.registerTool({name:'reset_car',description:'Regroup the character and both vehicles at the map start, keeping the session score.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute(input:unknown){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object');reset();return{status:'reset',score:Math.floor(score)}}},options)).catch(()=>{})}catch{}}

 window.addEventListener('keydown',down,options);window.addEventListener('keyup',up,options);window.addEventListener('blur',blur,options);window.addEventListener('resize',resize,options);renderer.domElement.addEventListener('pointerdown',pointerDown,options);renderer.domElement.addEventListener('pointermove',pointerMove,options);renderer.domElement.addEventListener('pointerup',pointerUp,options);renderer.domElement.addEventListener('pointercancel',pointerUp,options);reset();raf=requestAnimationFrame(loop);
 return{start(){active=true;paused=false;ensureAudio();host.focus()},pause,reset,key,menu,selectMap,interact,mute(m:boolean){muted=m},dispose(){lifecycle.abort();disposed=true;cancelAnimationFrame(raf);void audio?.close();scene.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();const ms=Array.isArray(o.material)?o.material:[o.material];ms.forEach(m=>m.dispose());if(o instanceof T.InstancedMesh)o.dispose()}});smoke.forEach(p=>p.s.material.dispose());town?.textures.forEach(t=>t.dispose());motorbike.textures.forEach(t=>t.dispose());parking.textures.forEach(t=>t.dispose());roadGrain.dispose();smokeTex.dispose();env.dispose();effects.dispose();renderer.dispose();renderer.domElement.remove()}};
}
