import * as T from 'three';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';

type HUD={speed:number,score:number,combo:number,angle:number,drifting:boolean};
export function createGame(host:HTMLElement,onHUD:(h:HUD)=>void,onPause:(p:boolean)=>void){
 const scene=new T.Scene();scene.background=new T.Color('#80959e');scene.fog=new T.FogExp2('#9ba6a8',.0025);
 const renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;host.appendChild(renderer.domElement);
 const camera=new T.PerspectiveCamera(48,innerWidth/innerHeight,.1,1600);
 const pmrem=new T.PMREMGenerator(renderer),room=new RoomEnvironment();const env=pmrem.fromScene(room,.04);scene.environment=env.texture;room.dispose();pmrem.dispose();
 scene.add(new T.HemisphereLight('#afdaff','#524635',2.3));const sun=new T.DirectionalLight('#ffe0a1',4.2);sun.position.set(-90,80,-130);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-100,right:100,top:100,bottom:-100,near:1,far:350});sun.shadow.bias=-.0005;scene.add(sun,sun.target);
 const sky=new T.Mesh(new T.SphereGeometry(1300,40,24),new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms:{},vertexShader:'varying vec3 v;void main(){v=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec3 v;void main(){float h=normalize(v).y;vec3 c=mix(vec3(.98,.65,.39),vec3(.29,.48,.64),smoothstep(-.08,.6,h));gl_FragColor=vec4(c,1.);}'}));scene.add(sky);
 const sunDisc=new T.Mesh(new T.SphereGeometry(23,32,16),new T.MeshBasicMaterial({color:'#ffe0a1',fog:false}));sunDisc.position.set(-440,105,-780);scene.add(sunDisc);
 const mat=(color:string,roughness=.8,metalness=0)=>new T.MeshStandardMaterial({color,roughness,metalness});
 const asphalt=mat('#363e41',.88),sand=mat('#8c846b'),white=mat('#e3d9c2'),red=mat('#ba5c45'),dark=mat('#0b141a',.4),metal=mat('#a5b3b9',.25,.85);
 function mesh(g:T.BufferGeometry,m:T.Material,x=0,y=0,z=0,parent:T.Object3D=scene){const a=new T.Mesh(g,m);a.position.set(x,y,z);a.castShadow=true;a.receiveShadow=true;parent.add(a);return a}
 const ground=mesh(new T.PlaneGeometry(1000,1250),sand,325,-.13,0);ground.rotation.x=-Math.PI/2;
 const sea=mesh(new T.PlaneGeometry(1600,1500,1,1),new T.MeshStandardMaterial({color:'#46767e',metalness:.65,roughness:.27}),-810,-1.2,0);sea.rotation.x=-Math.PI/2;
 // The circuit is a closed flowing spline with room to drift on each side.
 const points=[[-92,8],[-75,-78],[-12,-121],[78,-101],[122,-36],[90,28],[113,106],[30,140],[-43,109],[-54,59]].map(([x,z])=>new T.Vector3(x,0,z));
 const curve=new T.CatmullRomCurve3(points,true,'catmullrom',.5);const samples=curve.getSpacedPoints(400);const roadHalf=12.5;
 function ribbon(a:number,b:number,y:number,m:T.Material){const pos:number[]=[],idx:number[]=[];for(let i=0;i<=400;i++){const p=samples[i];const t=curve.getTangentAt(i/400);const n=new T.Vector3(-t.z,0,t.x);for(const off of [a,b])pos.push(p.x+n.x*off,y,p.z+n.z*off);if(i<400){let j=i*2;idx.push(j,j+2,j+1,j+1,j+2,j+3)}}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(pos,3));for(let k=0;k<idx.length;k+=3){[idx[k+1],idx[k+2]]=[idx[k+2],idx[k+1]]}g.setIndex(idx);g.computeVertexNormals();const o=mesh(g,m);o.castShadow=false;return o}
 ribbon(-roadHalf,roadHalf,0,asphalt);ribbon(-13.5,-12.4,.01,white);ribbon(12.4,13.5,.01,white);
 for(let i=0;i<400;i+=2){const p=samples[i],t=curve.getTangentAt(i/400);const n=new T.Vector3(-t.z,0,t.x);for(const side of [-1,1]){const curb=mesh(new T.BoxGeometry(.9,.08,2.7),i%4===0?red:white,p.x+n.x*13*side,.02,p.z+n.z*13*side);curb.rotation.y=Math.atan2(t.x,t.z)}}
 for(let i=0;i<400;i+=5){const p=samples[i],t=curve.getTangentAt(i/400);const a=mesh(new T.PlaneGeometry(.15,2.5),white,p.x,.016,p.z);a.rotation.set(-Math.PI/2,0,-Math.atan2(t.x,t.z));}
 // Scenic mountain ridges, pines, floodlights and trackside safety barriers.
 let seed=318;function random(){seed=(seed*16807)%2147483647;return(seed-1)/2147483646}
 for(let i=0;i<42;i++){const x=190+random()*400,z=-450+random()*900,h=35+random()*160;const mountain=mesh(new T.ConeGeometry(45+random()*90,h,5),mat(i%2?'#657678':'#71817e'),x,h*.5-3,z);mountain.rotation.y=random()*6;}
 function tree(x:number,z:number,s:number){mesh(new T.CylinderGeometry(.2*s,.35*s,5*s,6),mat('#665744'),x,2*s,z);for(let j=0;j<3;j++)mesh(new T.ConeGeometry((2.5-j*.5)*s,4*s,7),mat(j%2?'#3c5750':'#425a51'),x,(4+j*1.4)*s,z)}
 for(let i=0;i<120;i++){const x=-135+random()*360,z=-230+random()*460;const d=Math.min(...samples.filter((_,j)=>j%4===0).map(p=>Math.hypot(p.x-x,p.z-z)));if(d>23)tree(x,z,.8+random()*1.2)}
 for(let i=0;i<400;i+=16){const p=samples[i],t=curve.getTangentAt(i/400),n=new T.Vector3(-t.z,0,t.x);for(const side of [-1,1]){const x=p.x+n.x*17*side,z=p.z+n.z*17*side;const bar=mesh(new T.BoxGeometry(.3,.65,9),metal,x,.9,z);bar.rotation.y=Math.atan2(t.x,t.z);mesh(new T.CylinderGeometry(.08,.08,1.2,6),metal,x,.5,z)}if(i%32===0){const x=p.x+n.x*20,z=p.z+n.z*20;mesh(new T.CylinderGeometry(.12,.2,9,8),dark,x,4.4,z);const lamp=mesh(new T.BoxGeometry(2,.13,.8),new T.MeshStandardMaterial({color:'#fff4cb',emissive:'#ffd38c',emissiveIntensity:3}),x,9,z);lamp.rotation.z=.12}}
 // Sculpted coupe: shaped cross sections, separate glass canopy, fenders and aero.
 const car=new T.Group();scene.add(car);const paint=new T.MeshPhysicalMaterial({color:'#cbdcbd',metalness:.72,roughness:.24,clearcoat:1,clearcoatRoughness:.12});const glass=new T.MeshPhysicalMaterial({color:'#122a35',metalness:.7,roughness:.14,clearcoat:1});
 function loft(rows:number[][],material:T.Material){const v:number[]=[],ix:number[]=[];for(const [z,w,lower,shoulder,top]of rows){v.push(-w,lower,z,-w,shoulder,z,-w*.78,top,z,w*.78,top,z,w,shoulder,z,w,lower,z)}for(let j=0;j<rows.length-1;j++)for(let k=0;k<6;k++){const a=j*6+k,b=j*6+(k+1)%6;ix.push(a,b,a+6,b,b+6,a+6)}ix.push(0,2,1,0,3,2,0,5,3,3,5,4);const a=(rows.length-1)*6;ix.push(a,a+1,a+2,a,a+2,a+3,a,a+3,a+5,a+3,a+4,a+5);const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(v,3));for(let k=0;k<ix.length;k+=3){[ix[k+1],ix[k+2]]=[ix[k+2],ix[k+1]]}g.setIndex(ix);g.computeVertexNormals();return mesh(g,material,0,0,0,car)}
 loft([[-2.45,.81,.32,.52,.58],[-2.08,1,.3,.7,.76],[-1.38,1.01,.32,.85,.88],[-.65,.95,.34,.78,.85],[.7,.98,.34,.83,.9],[1.55,1.06,.32,.88,.94],[2.18,1.01,.34,.74,.8],[2.4,.88,.4,.68,.71]],paint);
 loft([[-.97,.83,.81,.84,.87],[-.36,.73,.85,1.34,1.42],[.65,.76,.85,1.38,1.47],[1.37,.87,.83,.9,.94]],glass);
 loft([[-.32,.75,1.37,1.4,1.44],[.68,.77,1.41,1.44,1.48]],paint);
 const wheels:T.Group[]=[];for(const x of [-1.02,1.02])for(const z of [-1.43,1.48]){const pivot=new T.Group();pivot.position.set(x,.45,z);car.add(pivot);wheels.push(pivot);const tire=mesh(new T.CylinderGeometry(.43,.43,.31,32),mat('#13171a',.96),0,0,0,pivot);tire.rotation.z=Math.PI/2;const rim=mesh(new T.CylinderGeometry(.3,.3,.325,24),mat('#323d43',.28,.9),0,0,0,pivot);rim.rotation.z=Math.PI/2;for(let k=0;k<5;k++){const spoke=mesh(new T.BoxGeometry(.34,.055,.54),metal,0,0,0,pivot);spoke.rotation.x=k*Math.PI/5}const hub=mesh(new T.CylinderGeometry(.09,.09,.35,12),metal,0,0,0,pivot);hub.rotation.z=Math.PI/2;}
 for(const side of [-1,1]){const skirt=mesh(new T.BoxGeometry(.1,.13,2.2),dark,side*1.01,.34,0,car);mesh(new T.BoxGeometry(.23,.11,.34),paint,side*1.0,1.02,-.54,car);mesh(new T.BoxGeometry(.025,.035,.24),metal,side*.966,.83,.45,car);for(const z of [-1.43,1.48]){const arch=mesh(new T.TorusGeometry(.47,.065,8,24,Math.PI),paint,side*1.015,.45,z,car);arch.rotation.y=Math.PI/2}}
 mesh(new T.BoxGeometry(1.8,.09,.4),dark,0,.31,-2.28,car);mesh(new T.BoxGeometry(1.5,.21,.04),dark,0,.46,-2.445,car);
 const headMat=new T.MeshStandardMaterial({color:'#e4faff',emissive:'#bceaff',emissiveIntensity:4});const tailMat=new T.MeshStandardMaterial({color:'#ff3730',emissive:'#ff1609',emissiveIntensity:3});
 for(const x of [-.64,.64]){const h=mesh(new T.BoxGeometry(.44,.065,.05),headMat,x,.62,-2.33,car);h.rotation.y=x*.12;mesh(new T.BoxGeometry(.5,.07,.04),tailMat,x,.68,2.35,car);const exhaust=mesh(new T.CylinderGeometry(.095,.095,.2,14),metal,x,.37,2.39,car);exhaust.rotation.x=Math.PI/2;}
 mesh(new T.BoxGeometry(1.88,.07,.36),dark,0,1.02,2.05,car);for(const x of [-.6,.6])mesh(new T.BoxGeometry(.07,.24,.1),dark,x,.89,2.05,car);
 const plate=mesh(new T.BoxGeometry(.48,.12,.02),white,0,.52,2.405,car);
 // Reusable smoke sprites and skid segments keep long sessions lightweight.
 const cv=document.createElement('canvas');cv.width=cv.height=64;const ctx=cv.getContext('2d')!;const grad=ctx.createRadialGradient(32,32,0,32,32,32);grad.addColorStop(0,'rgba(220,226,221,.5)');grad.addColorStop(1,'rgba(220,226,221,0)');ctx.fillStyle=grad;ctx.fillRect(0,0,64,64);const smokeTex=new T.CanvasTexture(cv);
 const smoke=Array.from({length:100},()=>{const s=new T.Sprite(new T.SpriteMaterial({map:smokeTex,transparent:true,depthWrite:false,opacity:0}));scene.add(s);return{s,life:0}});let smokeIndex=0;
 const skidMat=new T.MeshBasicMaterial({color:'#11191c',transparent:true,opacity:.45,depthWrite:false});const skids=Array.from({length:500},()=>{const s=mesh(new T.PlaneGeometry(.24,.7),skidMat);s.rotation.x=-Math.PI/2;s.visible=false;s.castShadow=false;return s});let skidIndex=0;
 const keys:Record<string,boolean>={};let active=false,paused=false,disposed=false,muted=false,yaw=0,vx=0,vz=0,steer=0,score=0,combo=0,driftGrace=0,frame=0,clock=0,raf=0,accum=0;
 let audio:AudioContext|null=null,osc:OscillatorNode|null=null,gain:GainNode|null=null;
 function ensureAudio(){if(!audio){audio=new AudioContext();osc=audio.createOscillator();osc.type='sawtooth';gain=audio.createGain();gain.gain.value=0;const filter=audio.createBiquadFilter();filter.type='lowpass';filter.frequency.value=280;osc.connect(filter).connect(gain).connect(audio.destination);osc.start()}void audio.resume()}
 function reset(){const p=curve.getPointAt(.03),t=curve.getTangentAt(.03);car.position.set(p.x,0,p.z);yaw=Math.atan2(-t.x,-t.z);car.rotation.set(0,yaw,0);vx=vz=steer=combo=0;for(const k in keys)keys[k]=false;updateCamera(1);}
 function updateCamera(dt:number){const forward=new T.Vector3(-Math.sin(yaw),0,-Math.cos(yaw));let target:T.Vector3;if(!active){target=car.position.clone().add(new T.Vector3(-9,4.7,9));camera.position.lerp(target,Math.min(1,dt*2));camera.lookAt(car.position.clone().add(new T.Vector3(-3.2,.7,0)))}else{target=car.position.clone().addScaledVector(forward,-8.8-Math.min(3,Math.hypot(vx,vz)*.07));target.y=4.5;camera.position.lerp(target,1-Math.exp(-dt*5));camera.lookAt(car.position.clone().addScaledVector(forward,4).add(new T.Vector3(0,.8,0)))} }
 function physics(dt:number){const speed=Math.hypot(vx,vz),fx=-Math.sin(yaw),fz=-Math.cos(yaw),rx=Math.cos(yaw),rz=-Math.sin(yaw);let longitudinal=vx*fx+vz*fz,lateral=vx*rx+vz*rz;const throttle=(keys.W?1:0)-(keys.S?1:0);const turn=(keys.A?1:0)-(keys.D?1:0),brake=!!keys.SPACE;
 steer+=(turn-steer)*Math.min(1,dt*9);longitudinal+=throttle*(throttle*longitudinal<0?27:17)*dt;longitudinal*=Math.exp(-(brake?1.2:.16+speed*.0016)*dt);longitudinal=T.MathUtils.clamp(longitudinal,-12,57);
 const slip=brake&&speed>5;const grip=slip?1.1:Math.abs(steer)>.2&&speed>12?3.2:7.0;lateral*=Math.exp(-grip*dt);
 yaw+=steer*Math.min(Math.abs(longitudinal)/8,1)*(1.05+speed*.009)*(longitudinal<0?-1:1)*dt*(slip?1.65:1);
 vx=fx*longitudinal+rx*lateral;vz=fz*longitudinal+rz*lateral;car.position.x+=vx*dt;car.position.z+=vz*dt;
 let nearest=0,dist=Infinity;for(let i=0;i<400;i++){const d=(car.position.x-samples[i].x)**2+(car.position.z-samples[i].z)**2;if(d<dist){dist=d;nearest=i}}const off=Math.sqrt(dist);if(off>roadHalf+1){vx*=Math.exp(-dt*1.5);vz*=Math.exp(-dt*1.5)}if(off>16){const p=samples[nearest],nx=(car.position.x-p.x)/off,nz=(car.position.z-p.z)/off;car.position.x=p.x+nx*16;car.position.z=p.z+nz*16;const outward=vx*nx+vz*nz;if(outward>0){vx-=nx*outward*1.4;vz-=nz*outward*1.4}combo=0}
 const slipAngle=Math.abs(Math.atan2(lateral,Math.abs(longitudinal)))*180/Math.PI;const drifting=speed>7&&off<roadHalf+1&&(slipAngle>9||slip&&Math.abs(steer)>.2);if(drifting){const points=dt*speed*(1+Math.min(slipAngle,60)/15);score+=points;combo+=points;driftGrace=1}else{driftGrace-=dt;if(driftGrace<=0)combo=0}
 car.rotation.set(0,yaw,-steer*Math.min(.035,speed*.001));tailMat.emissiveIntensity=brake||keys.S?7:2;
 wheels.forEach((w,i)=>{w.rotation.y=i%2===0?-steer*.4:0;w.children.forEach(c=>{if(c instanceof T.Mesh && c.geometry.type==='BoxGeometry')c.rotation.x+=longitudinal*dt/.43})});
 if(drifting&&frame%3===0){for(const side of [-1,1]){const pos=new T.Vector3(side, .1,1.5).applyAxisAngle(new T.Vector3(0,1,0),yaw).add(car.position);const puff=smoke[smokeIndex++%smoke.length];puff.s.position.copy(pos);puff.life=1;puff.s.scale.setScalar(.6);const skid=skids[skidIndex++%skids.length];skid.visible=true;skid.position.set(pos.x,.027,pos.z);skid.rotation.z=-Math.atan2(vx,vz)}}
 if(frame%6===0)onHUD({speed:Math.hypot(vx,vz)*3.6,score,combo,angle:slipAngle,drifting});if(osc&&gain&&audio){osc.frequency.setTargetAtTime(35+speed*2.6+(keys.W?20:0),audio.currentTime,.08);gain.gain.setTargetAtTime(muted?0:.025+(keys.W?.025:0),audio.currentTime,.1)}
 }
 function loop(now:number){if(disposed)return;const dt=Math.min((now-clock)/1000||.016,.05);clock=now;frame++;if(active&&!paused){accum+=dt;while(accum>=1/120){physics(1/120);accum-=1/120}}for(const p of smoke){if(p.life>0&&!paused){p.life-=dt*.55;p.s.position.y+=dt*.6;p.s.scale.addScalar(dt*1.7);p.s.material.opacity=Math.max(0,p.life*.45)}}updateCamera(dt);sun.position.set(car.position.x-90,80,car.position.z-130);sun.target.position.copy(car.position);renderer.render(scene,camera);raf=requestAnimationFrame(loop)}
 function pause(){if(!active)return;paused=!paused;for(const k in keys)keys[k]=false;onPause(paused);if(gain&&audio)gain.gain.setTargetAtTime(0,audio.currentTime,.03)}
 function key(k:string,down:boolean){keys[k]=down}
 function down(e:KeyboardEvent){const k=e.code==='Space'?'SPACE':e.code.replace('Key','').replace('ArrowUp','W').replace('ArrowDown','S').replace('ArrowLeft','A').replace('ArrowRight','D');if(['W','A','S','D','SPACE','Escape','R'].includes(k)){e.preventDefault();if(k==='Escape'&&!e.repeat)pause();else if(k==='R'&&!e.repeat)reset();else keys[k]=true}}
 function up(e:KeyboardEvent){const k=e.code==='Space'?'SPACE':e.code.replace('Key','').replace('ArrowUp','W').replace('ArrowDown','S').replace('ArrowLeft','A').replace('ArrowRight','D');keys[k]=false}
 function blur(){if(active&&!paused)pause();for(const k in keys)keys[k]=false}
 function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)}
 const lifecycle=new AbortController();
 const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;
 if(context?.registerTool){try{Promise.resolve(context.registerTool({name:'reset_car',description:'Return the car to the starting line, keeping the session score.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute(input:unknown){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object');reset();return{status:'reset',score:Math.floor(score)}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}}
 window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);window.addEventListener('resize',resize);reset();raf=requestAnimationFrame(loop);
 return{start(){active=true;paused=false;ensureAudio();host.focus()},pause,reset,key,mute(m:boolean){muted=m},dispose(){lifecycle.abort();disposed=true;cancelAnimationFrame(raf);window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);window.removeEventListener('resize',resize);void audio?.close();scene.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();const ms=Array.isArray(o.material)?o.material:[o.material];ms.forEach(m=>m.dispose())}});smoke.forEach(p=>p.s.material.dispose());smokeTex.dispose();env.dispose();renderer.dispose();renderer.domElement.remove()}};
}
