import * as T from 'three';
import {createCharacter,createMotorbike} from './actors';
import {createEffects,grainTexture} from './visuals';
import {nearestVehicle,exitCandidates,type TravelMode} from './vehicle-state';
import { createParking, parkingCollision } from './parking';
import {createTown} from './town';
import {loadTownData} from './town-data';
import {loadCarModelMulti} from './car-multi-glb';
import {loadBikeModel} from './bike-glb';
import {loadBikeModelMulti,type BikeModel} from './bike-multi-glb';
import {CHUNK,SPACING,generateChunk,chunkKey,worldHeight,loadGenMapData,type GenOptions} from './gen-loader';
import {addCash} from './wallet-store';
import type {TownData} from './town-data';
import {createNpc,type NpcHandle} from './npc';
import {createRaceway,type RacewayHandle} from './racetrack';
import {createRing,type RingHandle} from './gen-ring';
import {createInteriorRoom,planInteriors,type InteriorDoor} from './interiors';
export type MapId='coast'|'costco'|'svitlodarsk'|'wurzburg'|'raceway'|'driftgrid';
const TOWN_MAPS=new Set<MapId>(['svitlodarsk','wurzburg','driftgrid']);
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';

export type DriveStyle='standard'|'drift';
export type VehicleId='coupe'|'sedan'|'hatchback'|'wagon'|'liftback'|'suv'|'cuv'|'porsche'|'m8'|'m4'|'mustang'|'bike'|'street'|'cruiser'|'chopper'|'scrambler'|'cafe'|'sportbike'|'sporttourer'|'tourer'|'adventure'|'mx'|'enduro'|'supermoto'|'pitbike'|'scooter'|'maxiscooter';
export type HUD={speed:number,score:number,combo:number,angle:number,drifting:boolean,x:number,z:number,yaw:number,mode:TravelMode,hint:string,carX:number,carZ:number,bikeX:number,bikeZ:number,style:DriveStyle,earned?:number,loading:boolean,sport:boolean,interior:boolean};
const CAR_GLB:Record<string,string>={coupe:'/models/coupe.glb',sedan:'/models/sedan.glb',hatchback:'/models/hatchback.glb',wagon:'/models/wagon.glb',liftback:'/models/liftback.glb',suv:'/models/suv.glb',cuv:'/models/cuv.glb',porsche:'/porshe.glb',m8:'/m8_gte.glb',m4:'/bmw_m4_gte.glb',mustang:'/ford_mustang.glb'};
const OLD_CAR_FLIP=new Set<VehicleId>(['porsche','m8','m4','mustang']);
const CAR_NAMES:Record<VehicleId,string>={coupe:'Sports Coupe',sedan:'Sedan',hatchback:'Hatchback',wagon:'Station Wagon',liftback:'Liftback',suv:'SUV',cuv:'Crossover',porsche:'Porsche',m8:'BMW M8 GTE',m4:'BMW M4 GT3',mustang:'Ford Mustang GT3',bike:'BMW S1000RR',street:'Street Naked',cruiser:'Cruiser',chopper:'Chopper',scrambler:'Scrambler',cafe:'Cafe Racer',sportbike:'Sportbike',sporttourer:'Sport Tourer',tourer:'Grand Tourer',adventure:'Adventure',mx:'Motocross',enduro:'Enduro',supermoto:'Supermoto',pitbike:'Pitbike',scooter:'Scooter',maxiscooter:'Maxi-Scooter'};
const BIKE_GLB:Record<string,string>={street:'/models/bike_street.glb',cruiser:'/models/bike_cruiser.glb',chopper:'/models/bike_chopper.glb',scrambler:'/models/bike_scrambler.glb',cafe:'/models/bike_cafe.glb',sportbike:'/models/bike_sportbike.glb',sporttourer:'/models/bike_sporttourer.glb',tourer:'/models/bike_tourer.glb',adventure:'/models/bike_adventure.glb',mx:'/models/bike_mx.glb',enduro:'/models/bike_enduro.glb',supermoto:'/models/bike_supermoto.glb',pitbike:'/models/bike_pitbike.glb',scooter:'/models/bike_scooter.glb',maxiscooter:'/models/bike_maxiscooter.glb'};
const BIKE_IDS=Object.keys(BIKE_GLB);
const isBikeId=(id:VehicleId)=>id==='bike'||(BIKE_IDS as string[]).includes(id);
const WURZBURG_SPAWN={x:-27,z:-160,yaw:-2.628};
const VIS_STEER=.4,CS_K=.35,CS_MAX=.35,SLOPE_K=5,REAR_K=.025,REAR_BASE=.05,REAR_DRIFT=.08;
const Q_MIN=18,Q_RANGE=27,Q_SPEED=25,RATE=3,FLIP_PTS=40,FLIP_MULT=1.4,MULT_MAX=5;
const HANDLING:Record<VehicleId,{accel:number,rev:number,max:number,maxRev:number,dragBase:number,dragLin:number,brakeDrag:number,grip:number,gripSteer:number,gripSlip:number,driftGrip:number,driftGripSteer:number,driftGripSlip:number,steer:number,steerSpeed:number,latYaw:number}>={
coupe:{accel:34,rev:48,max:114,maxRev:-24,dragBase:.16,dragLin:.0008,brakeDrag:.48,grip:1.65,gripSteer:.72,gripSlip:.24,driftGrip:3.85,driftGripSteer:2.35,driftGripSlip:.58,steer:1.68,steerSpeed:.0046,latYaw:.34},
sedan:{accel:36,rev:48,max:118,maxRev:-24,dragBase:.16,dragLin:.0008,brakeDrag:.48,grip:1.75,gripSteer:.82,gripSlip:.27,driftGrip:4.05,driftGripSteer:2.45,driftGripSlip:.6,steer:1.6,steerSpeed:.0044,latYaw:.3},
hatchback:{accel:38,rev:50,max:113,maxRev:-25,dragBase:.155,dragLin:.00078,brakeDrag:.47,grip:1.55,gripSteer:.68,gripSlip:.25,driftGrip:3.7,driftGripSteer:2.25,driftGripSlip:.56,steer:1.8,steerSpeed:.0048,latYaw:.38},
wagon:{accel:33,rev:45,max:115,maxRev:-23,dragBase:.17,dragLin:.00084,brakeDrag:.5,grip:2.0,gripSteer:.98,gripSlip:.32,driftGrip:4.5,driftGripSteer:2.75,driftGripSlip:.68,steer:1.5,steerSpeed:.004,latYaw:.27},
liftback:{accel:40,rev:50,max:122,maxRev:-25,dragBase:.16,dragLin:.0008,brakeDrag:.48,grip:1.6,gripSteer:.71,gripSlip:.24,driftGrip:3.8,driftGripSteer:2.3,driftGripSlip:.56,steer:1.75,steerSpeed:.0048,latYaw:.35},
suv:{accel:30,rev:42,max:106,maxRev:-21,dragBase:.18,dragLin:.0009,brakeDrag:.52,grip:2.35,gripSteer:1.15,gripSlip:.4,driftGrip:5.2,driftGripSteer:3.2,driftGripSlip:.82,steer:1.28,steerSpeed:.003,latYaw:.22},
cuv:{accel:32,rev:44,max:108,maxRev:-22,dragBase:.17,dragLin:.00086,brakeDrag:.5,grip:2.15,gripSteer:1.0,gripSlip:.34,driftGrip:4.85,driftGripSteer:2.9,driftGripSlip:.74,steer:1.4,steerSpeed:.0036,latYaw:.27},
porsche:{accel:43,rev:52,max:126,maxRev:-26,dragBase:.155,dragLin:.00078,brakeDrag:.46,grip:1.45,gripSteer:.62,gripSlip:.22,driftGrip:3.15,driftGripSteer:1.95,driftGripSlip:.48,steer:2.05,steerSpeed:.0052,latYaw:.42},
m8:{accel:40,rev:47,max:136,maxRev:-23,dragBase:.17,dragLin:.00085,brakeDrag:.5,grip:2.1,gripSteer:1.0,gripSlip:.36,driftGrip:4.75,driftGripSteer:2.8,driftGripSlip:.7,steer:1.45,steerSpeed:.0036,latYaw:.27},
m4:{accel:45,rev:50,max:141,maxRev:-24,dragBase:.165,dragLin:.00082,brakeDrag:.48,grip:2.3,gripSteer:1.15,gripSlip:.4,driftGrip:5.05,driftGripSteer:3.0,driftGripSlip:.74,steer:1.6,steerSpeed:.004,latYaw:.26},
mustang:{accel:46,rev:48,max:138,maxRev:-24,dragBase:.17,dragLin:.00088,brakeDrag:.5,grip:1.35,gripSteer:.58,gripSlip:.21,driftGrip:3.1,driftGripSteer:1.85,driftGripSlip:.46,steer:1.9,steerSpeed:.0048,latYaw:.48},
bike:{accel:0,rev:0,max:0,maxRev:0,dragBase:0,dragLin:0,brakeDrag:0,grip:0,gripSteer:0,gripSlip:0,driftGrip:0,driftGripSteer:0,driftGripSlip:0,steer:0,steerSpeed:0,latYaw:0},
street:{accel:0,rev:0,max:0,maxRev:0,dragBase:0,dragLin:0,brakeDrag:0,grip:0,gripSteer:0,gripSlip:0,driftGrip:0,driftGripSteer:0,driftGripSlip:0,steer:0,steerSpeed:0,latYaw:0},
cruiser:{accel:0,rev:0,max:0,maxRev:0,dragBase:0,dragLin:0,brakeDrag:0,grip:0,gripSteer:0,gripSlip:0,driftGrip:0,driftGripSteer:0,driftGripSlip:0,steer:0,steerSpeed:0,latYaw:0},
chopper:{accel:0,rev:0,max:0,maxRev:0,dragBase:0,dragLin:0,brakeDrag:0,grip:0,gripSteer:0,gripSlip:0,driftGrip:0,driftGripSteer:0,driftGripSlip:0,steer:0,steerSpeed:0,latYaw:0},
scrambler:{accel:0,rev:0,max:0,maxRev:0,dragBase:0,dragLin:0,brakeDrag:0,grip:0,gripSteer:0,gripSlip:0,driftGrip:0,driftGripSteer:0,driftGripSlip:0,steer:0,steerSpeed:0,latYaw:0},
cafe:{accel:0,rev:0,max:0,maxRev:0,dragBase:0,dragLin:0,brakeDrag:0,grip:0,gripSteer:0,gripSlip:0,driftGrip:0,driftGripSteer:0,driftGripSlip:0,steer:0,steerSpeed:0,latYaw:0},
sportbike:{accel:0,rev:0,max:0,maxRev:0,dragBase:0,dragLin:0,brakeDrag:0,grip:0,gripSteer:0,gripSlip:0,driftGrip:0,driftGripSteer:0,driftGripSlip:0,steer:0,steerSpeed:0,latYaw:0},
sporttourer:{accel:0,rev:0,max:0,maxRev:0,dragBase:0,dragLin:0,brakeDrag:0,grip:0,gripSteer:0,gripSlip:0,driftGrip:0,driftGripSteer:0,driftGripSlip:0,steer:0,steerSpeed:0,latYaw:0},
tourer:{accel:0,rev:0,max:0,maxRev:0,dragBase:0,dragLin:0,brakeDrag:0,grip:0,gripSteer:0,gripSlip:0,driftGrip:0,driftGripSteer:0,driftGripSlip:0,steer:0,steerSpeed:0,latYaw:0},
adventure:{accel:0,rev:0,max:0,maxRev:0,dragBase:0,dragLin:0,brakeDrag:0,grip:0,gripSteer:0,gripSlip:0,driftGrip:0,driftGripSteer:0,driftGripSlip:0,steer:0,steerSpeed:0,latYaw:0},
mx:{accel:0,rev:0,max:0,maxRev:0,dragBase:0,dragLin:0,brakeDrag:0,grip:0,gripSteer:0,gripSlip:0,driftGrip:0,driftGripSteer:0,driftGripSlip:0,steer:0,steerSpeed:0,latYaw:0},
enduro:{accel:0,rev:0,max:0,maxRev:0,dragBase:0,dragLin:0,brakeDrag:0,grip:0,gripSteer:0,gripSlip:0,driftGrip:0,driftGripSteer:0,driftGripSlip:0,steer:0,steerSpeed:0,latYaw:0},
supermoto:{accel:0,rev:0,max:0,maxRev:0,dragBase:0,dragLin:0,brakeDrag:0,grip:0,gripSteer:0,gripSlip:0,driftGrip:0,driftGripSteer:0,driftGripSlip:0,steer:0,steerSpeed:0,latYaw:0},
pitbike:{accel:0,rev:0,max:0,maxRev:0,dragBase:0,dragLin:0,brakeDrag:0,grip:0,gripSteer:0,gripSlip:0,driftGrip:0,driftGripSteer:0,driftGripSlip:0,steer:0,steerSpeed:0,latYaw:0},
scooter:{accel:0,rev:0,max:0,maxRev:0,dragBase:0,dragLin:0,brakeDrag:0,grip:0,gripSteer:0,gripSlip:0,driftGrip:0,driftGripSteer:0,driftGripSlip:0,steer:0,steerSpeed:0,latYaw:0},
maxiscooter:{accel:0,rev:0,max:0,maxRev:0,dragBase:0,dragLin:0,brakeDrag:0,grip:0,gripSteer:0,gripSlip:0,driftGrip:0,driftGripSteer:0,driftGripSlip:0,steer:0,steerSpeed:0,latYaw:0}};
export function createGame(host:HTMLElement,onHUD:(h:HUD)=>void,onPause:(p:boolean)=>void){
 const scene=new T.Scene();scene.background=new T.Color('#80959e');scene.fog=new T.FogExp2('#9ba6a8',.0025);
 const renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});const nav=navigator as Navigator&{deviceMemory?:number};const LOW=navigator.maxTouchPoints>=1||window.matchMedia('(pointer:coarse)').matches||(nav.deviceMemory??8)<=4||(navigator.hardwareConcurrency||8)<=4;renderer.setPixelRatio(LOW?1:Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;host.appendChild(renderer.domElement);
 const camera=new T.PerspectiveCamera(48,innerWidth/innerHeight,.1,LOW?4000:8000);
 const pmrem=new T.PMREMGenerator(renderer),room=new RoomEnvironment();const env=pmrem.fromScene(room,.04);scene.environment=env.texture;room.dispose();pmrem.dispose();
scene.add(new T.HemisphereLight('#afdaff','#524635',1.6));const sun=new T.DirectionalLight('#ffe0a1',3.8);sun.position.set(-90,80,-130);sun.castShadow=true;sun.shadow.mapSize.set(LOW?1024:2048,LOW?1024:2048);Object.assign(sun.shadow.camera,{left:-45,right:45,top:45,bottom:-45,near:1,far:250});sun.shadow.bias=-.0005;sun.shadow.radius=8;scene.add(sun,sun.target);
const effects=createEffects(renderer,scene,camera,LOW?.6:1);
 const sky=new T.Mesh(new T.SphereGeometry(1300,40,24),new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms:{},vertexShader:'varying vec3 v;void main(){v=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec3 v;float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.54);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+vec2(1,1)),f.x),f.y);}void main(){vec3 n=normalize(v);float h=n.y;vec3 c=mix(vec3(.98,.65,.39),vec3(.29,.48,.64),smoothstep(-.08,.6,h));vec2 p=n.xz/(max(.1,h)+.2)*3.;float f=noise(p)*.6+noise(p*2.1)*.3+noise(p*4.3)*.1;float clouds=smoothstep(.48,.76,f)*smoothstep(.02,.3,h);c=mix(c,vec3(.86,.86,.81),clouds*.75);gl_FragColor=vec4(c,1.);}'}));scene.add(sky);
 const sunDisc=new T.Mesh(new T.SphereGeometry(23,32,16),new T.MeshBasicMaterial({color:'#ffe0a1',fog:false}));sunDisc.position.set(-440,105,-780);scene.add(sunDisc);
 const mat=(color:string,roughness=.8,metalness=0)=>new T.MeshStandardMaterial({color,roughness,metalness});
 const roadGrain=grainTexture();
 const asphalt=mat('#363e41',.75),sand=mat('#8c846b'),white=mat('#e3d9c2'),red=mat('#ba5c45'),dark=mat('#0b141a',.4),metal=mat('#a5b3b9',.25,.85);
 asphalt.bumpMap=roadGrain;asphalt.bumpScale=.035;
 let worldRoot:T.Object3D=scene;
 function mesh(g:T.BufferGeometry,m:T.Material,x=0,y=0,z=0,parent:T.Object3D=worldRoot){const a=new T.Mesh(g,m);a.position.set(x,y,z);a.castShadow=true;a.receiveShadow=true;parent.add(a);return a}
 const coast=new T.Group();scene.add(coast);worldRoot=coast;
 const ground=mesh(new T.PlaneGeometry(1000,1250),sand,325,-.13,0);ground.rotation.x=-Math.PI/2;
 const sea=mesh(new T.PlaneGeometry(1600,1500,1,1),new T.MeshStandardMaterial({color:'#46767e',metalness:.65,roughness:.27}),-810,-1.2,0);sea.rotation.x=-Math.PI/2;
 // The circuit is a closed flowing spline with room to drift on each side.
 const points=[[-92,8],[-75,-78],[-12,-121],[78,-101],[122,-36],[90,28],[113,106],[30,140],[-43,109],[-54,59]].map(([x,z])=>new T.Vector3(x,0,z));
 const curve=new T.CatmullRomCurve3(points,true,'catmullrom',.5);const samples=curve.getSpacedPoints(400);const roadHalf=12.5;
 function ribbon(a:number,b:number,y:number,m:T.Material){const pos:number[]=[],idx:number[]=[];for(let i=0;i<=400;i++){const p=samples[i];const t=curve.getTangentAt(i/400);const n=new T.Vector3(-t.z,0,t.x);for(const off of [a,b])pos.push(p.x+n.x*off,y,p.z+n.z*off);if(i<400){let j=i*2;idx.push(j,j+2,j+1,j+1,j+2,j+3)}}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(pos,3));for(let k=0;k<idx.length;k+=3){[idx[k+1],idx[k+2]]=[idx[k+2],idx[k+1]]}g.setIndex(idx);g.computeVertexNormals();const o=mesh(g,m);o.castShadow=false;return o}
 ribbon(-roadHalf,roadHalf,0,asphalt);ribbon(-13.5,-12.4,.01,white);ribbon(12.4,13.5,.01,white);
 for(let i=0;i<400;i+=2){const p=samples[i],t=curve.getTangentAt(i/400);const n=new T.Vector3(-t.z,0,t.x);for(const side of [-1,1]){const curb=mesh(new T.BoxGeometry(.9,.08,2.7),i%4===0?red:white,p.x+n.x*13*side,.02,p.z+n.z*13*side);curb.rotation.y=Math.atan2(t.x,t.z)}}
 for(let i=0;i<400;i+=5){const p=samples[i],t=curve.getTangentAt(i/400);const a=mesh(new T.PlaneGeometry(.15,2.5),white,p.x,.016,p.z);a.rotation.set(-Math.PI/2,0,-Math.atan2(t.x,t.z));}
 // Scenic mountain ridges, pines, floodlights and trackside safety barriers.
 let seed=318;function random(){seed=(seed*16807)%2147483647;return(seed-1)/2147483646}
 for(let i=0;i<42;i++){const x=190+random()*400,z=-450+random()*900,h=35+random()*160;const mountain=mesh(new T.ConeGeometry(45+random()*90,h,5),mat(i%2?'#657678':'#71817e'),x,h*.5-3,z);mountain.rotation.y=random()*6;}
 function tree(x:number,z:number,s:number){mesh(new T.CylinderGeometry(.2*s,.35*s,5*s,6),mat('#665744'),x,2*s,z);for(let j=0;j<3;j++)mesh(new T.ConeGeometry((2.5-j*.5)*s,4*s,7),mat(j%2?'#3c5750':'#425a51'),x,(4+j*1.4)*s,z)}
 for(let i=0;i<120;i++){const x=-135+random()*360,z=-230+random()*460;const d=Math.min(...samples.filter((_,j)=>j%4===0).map(p=>Math.hypot(p.x-x,p.z-z)));if(d>23)tree(x,z,.8+random()*1.2)}
 for(let i=0;i<400;i+=16){const p=samples[i],t=curve.getTangentAt(i/400),n=new T.Vector3(-t.z,0,t.x);for(const side of [-1,1]){const x=p.x+n.x*17*side,z=p.z+n.z*17*side;const bar=mesh(new T.BoxGeometry(.3,.65,9),metal,x,.9,z);bar.rotation.y=Math.atan2(t.x,t.z);mesh(new T.CylinderGeometry(.08,.08,1.2,6),metal,x,.5,z)}if(i%32===0){const x=p.x+n.x*20,z=p.z+n.z*20;mesh(new T.CylinderGeometry(.12,.2,9,8),dark,x,4.4,z);const lamp=mesh(new T.BoxGeometry(2,.13,.8),new T.MeshStandardMaterial({color:'#fff4cb',emissive:'#ffd38c',emissiveIntensity:3}),x,9,z);lamp.rotation.z=.12}}
 const parking=createParking();scene.add(parking.group);parking.group.visible=false;worldRoot=scene;let mapId:MapId='coast';let town:ReturnType<typeof createTown>|null=null;let npc:NpcHandle|null=null;const towns=new Map<MapId,ReturnType<typeof createTown>>();const genRoot=new T.Group();genRoot.visible=false;scene.add(genRoot);
  const raceway:RacewayHandle=createRaceway({scene});raceway.group.visible=false;
   const interiorRoom=createInteriorRoom(scene);let interiorDoors:InteriorDoor[]=[];let interior:null|InteriorDoor=null;
  // Only the vehicles cast shadows: environment (ground, road, pines, mountains,
  // curbs, barriers) receives light so no large dark slabs slide across the road.
  const castVehicles=(o:T.Object3D)=>o.traverse(x=>{if(x instanceof T.Mesh)x.castShadow=true});
  coast.traverse(o=>{if(o instanceof T.Mesh)o.castShadow=false});
  // Sculpted coupe: shaped cross sections, separate glass canopy, fenders and aero.
  const VEHICLE_SCALE=1.1;const car=new T.Group();scene.add(car);const pCar=new T.Group();car.add(pCar);pCar.scale.setScalar(VEHICLE_SCALE);const paint=new T.MeshPhysicalMaterial({color:'#cbdcbd',metalness:.72,roughness:.24,clearcoat:1,clearcoatRoughness:.12});const glass=new T.MeshPhysicalMaterial({color:'#122a35',metalness:.7,roughness:.14,clearcoat:1});
  function loft(rows:number[][],material:T.Material){const v:number[]=[],ix:number[]=[];for(const [z,w,lower,shoulder,top]of rows){v.push(-w,lower,z,-w,shoulder,z,-w*.78,top,z,w*.78,top,z,w,shoulder,z,w,lower,z)}for(let j=0;j<rows.length-1;j++)for(let k=0;k<6;k++){const a=j*6+k,b=j*6+(k+1)%6;ix.push(a,b,a+6,b,b+6,a+6)}ix.push(0,2,1,0,3,2,0,5,3,3,5,4);const a=(rows.length-1)*6;ix.push(a,a+1,a+2,a,a+2,a+3,a,a+3,a+5,a+3,a+4,a+5);const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(v,3));for(let k=0;k<ix.length;k+=3){[ix[k+1],ix[k+2]]=[ix[k+2],ix[k+1]]}g.setIndex(ix);g.computeVertexNormals();return mesh(g,material,0,0,0,pCar)}
 loft([[-2.45,.81,.32,.52,.58],[-2.08,1,.3,.7,.76],[-1.38,1.01,.32,.85,.88],[-.65,.95,.34,.78,.85],[.7,.98,.34,.83,.9],[1.55,1.06,.32,.88,.94],[2.18,1.01,.34,.74,.8],[2.4,.88,.4,.68,.71]],paint);
 loft([[-.97,.83,.81,.84,.87],[-.36,.73,.85,1.34,1.42],[.65,.76,.85,1.38,1.47],[1.37,.87,.83,.9,.94]],glass);
 loft([[-.32,.75,1.37,1.4,1.44],[.68,.77,1.41,1.44,1.48]],paint);
  let wheels:T.Group[]=[];for(const x of [-1.02,1.02])for(const z of [-1.43,1.48]){const pivot=new T.Group();pivot.position.set(x,.45,z);pCar.add(pivot);wheels.push(pivot);const tire=mesh(new T.CylinderGeometry(.43,.43,.31,32),mat('#13171a',.96),0,0,0,pivot);tire.rotation.z=Math.PI/2;const rim=mesh(new T.CylinderGeometry(.3,.3,.325,24),mat('#323d43',.28,.9),0,0,0,pivot);rim.rotation.z=Math.PI/2;for(let k=0;k<5;k++){const spoke=mesh(new T.BoxGeometry(.34,.055,.54),metal,0,0,0,pivot);spoke.rotation.x=k*Math.PI/5}const hub=mesh(new T.CylinderGeometry(.09,.09,.35,12),metal,0,0,0,pivot);hub.rotation.z=Math.PI/2;}
  for(const side of [-1,1]){const skirt=mesh(new T.BoxGeometry(.1,.13,2.2),dark,side*1.01,.34,0,pCar);mesh(new T.BoxGeometry(.23,.11,.34),paint,side*1.0,1.02,-.54,pCar);mesh(new T.BoxGeometry(.025,.035,.24),metal,side*.966,.83,.45,pCar);for(const z of [-1.43,1.48]){const arch=mesh(new T.TorusGeometry(.47,.065,8,24,Math.PI),paint,side*1.015,.45,z,pCar);arch.rotation.y=Math.PI/2}}
  mesh(new T.BoxGeometry(1.8,.09,.4),dark,0,.31,-2.28,pCar);mesh(new T.BoxGeometry(1.5,.21,.04),dark,0,.46,-2.445,pCar);
  const headMat=new T.MeshStandardMaterial({color:'#e4faff',emissive:'#bceaff',emissiveIntensity:4});let tailMat=new T.MeshStandardMaterial({color:'#ff3730',emissive:'#ff1609',emissiveIntensity:3});
  for(const x of [-.64,.64]){const h=mesh(new T.BoxGeometry(.44,.065,.05),headMat,x,.62,-2.33,pCar);h.rotation.y=x*.12;mesh(new T.BoxGeometry(.5,.07,.04),tailMat,x,.68,2.35,pCar);const exhaust=mesh(new T.CylinderGeometry(.095,.095,.2,14),metal,x,.37,2.39,pCar);exhaust.rotation.x=Math.PI/2;}
  mesh(new T.BoxGeometry(1.88,.07,.36),dark,0,1.02,2.05,pCar);for(const x of [-.6,.6])mesh(new T.BoxGeometry(.07,.24,.1),dark,x,.89,2.05,pCar);
  const plate=mesh(new T.BoxGeometry(.48,.12,.02),white,0,.52,2.405,pCar);castVehicles(car);
 // Reusable smoke sprites and skid segments keep long sessions lightweight.
 const cv=document.createElement('canvas');cv.width=cv.height=64;const ctx=cv.getContext('2d')!;const grad=ctx.createRadialGradient(32,32,0,32,32,32);grad.addColorStop(0,'rgba(220,226,221,.5)');grad.addColorStop(1,'rgba(220,226,221,0)');ctx.fillStyle=grad;ctx.fillRect(0,0,64,64);const smokeTex=new T.CanvasTexture(cv);
 const smoke=Array.from({length:100},()=>{const s=new T.Sprite(new T.SpriteMaterial({map:smokeTex,transparent:true,depthWrite:false,opacity:0}));scene.add(s);return{s,life:0}});let smokeIndex=0;
 const skidMat=new T.MeshBasicMaterial({color:'#11191c',transparent:true,opacity:.45,depthWrite:false});const skids=Array.from({length:500},()=>{const s=mesh(new T.PlaneGeometry(.24,.7),skidMat);s.rotation.x=-Math.PI/2;s.visible=false;s.castShadow=false;return s});let skidIndex=0;
const motorbike=createMotorbike();scene.add(motorbike.group);const character=createCharacter();scene.add(character.group);castVehicles(motorbike.group);castVehicles(character.group);
  const carGroups:Record<string,T.Group>={coupe:car};for(const id of ['sedan','hatchback','wagon','liftback','suv','cuv','porsche','m8','m4','mustang'] as const){const g=new T.Group();g.scale.setScalar(VEHICLE_SCALE);g.visible=false;carGroups[id]=g;scene.add(g);castVehicles(g)}
  let showVehicles=false,selected:VehicleId='coupe',garage:Record<VehicleId,{group:T.Group,wheels:T.Group[],tailMat:T.MeshStandardMaterial|null,textures:T.Texture[]}|null>={coupe:{group:car,wheels,tailMat,textures:[]},sedan:null,hatchback:null,wagon:null,liftback:null,suv:null,cuv:null,porsche:null,m8:null,m4:null,mustang:null,bike:null,street:null,cruiser:null,chopper:null,scrambler:null,cafe:null,sportbike:null,sporttourer:null,tourer:null,adventure:null,mx:null,enduro:null,supermoto:null,pitbike:null,scooter:null,maxiscooter:null};
  const activeCar=()=>garage[selected]?.group??(selected==='coupe'||isBikeId(selected)?car:(garage.coupe?.group??car));
  const loadingCar=()=>selected!=='coupe'&&!isBikeId(selected)&&garage[selected]===null;
  const carName=()=>CAR_NAMES[isBikeId(selected)?'coupe':selected];
  const renderVehicles=()=>{const cg=activeCar();for(const[k,g]of Object.entries(carGroups))g.visible=showVehicles&&g===cg;motorbike.group.visible=showVehicles;character.group.visible=showVehicles};
  for(const g of Object.values(carGroups)){const light=new T.SpotLight('#ffe5b0',12,45,.45,.7,1);light.position.set(0,1,-1);light.target.position.set(0,.05,-25);light.userData.builtin=true;light.target.userData.builtin=true;g.add(light,light.target)}
  const light=new T.SpotLight('#ffe5b0',8,45,.45,.7,1);light.position.set(0,1,-1);light.target.position.set(0,.05,-25);light.userData.builtin=true;light.target.userData.builtin=true;motorbike.group.add(light,light.target);
  renderVehicles();
  // Swap in the detailed GLB models once they load; keep the procedural
  // vehicles as an instant fallback so the game starts without waiting.
  let glbBike=false;const glbTextures:T.Texture[]=[];let bmwGroup:T.Group|null=null;
  const bikeGarage:Record<string,BikeModel|null>={};for(const id of BIKE_IDS){bikeGarage[id]=null}
  const mountBike=(g:T.Group)=>{for(let i=motorbike.group.children.length-1;i>=0;i--){const c=motorbike.group.children[i];if(c.userData.builtin)continue;motorbike.group.remove(c)}motorbike.group.add(g);glbBike=true;renderVehicles();setLoad()};
  const setBikeModel=(id:string)=>{const m=bikeGarage[id];if(!m)return;mountBike(m.group)};
  const setLoad=()=>{(window as Window & {__load?:unknown}).__load={coupe:!!garage.coupe,sedan:!!garage.sedan,hatchback:!!garage.hatchback,wagon:!!garage.wagon,liftback:!!garage.liftback,suv:!!garage.suv,cuv:!!garage.cuv,porsche:!!garage.porsche,m8:!!garage.m8,m4:!!garage.m4,mustang:!!garage.mustang,bike:glbBike,...Object.fromEntries(BIKE_IDS.map(id=>[id,!!bikeGarage[id]]))}};
  for(const [id,url]of Object.entries(CAR_GLB)){void loadCarModelMulti(url,OLD_CAR_FLIP.has(id as VehicleId)).then(m=>{const vid=id as VehicleId;if(disposed||!m||garage[vid])return;const glbMark=(x:T.Group)=>{let tz=0,tn=0,hz=0,hn=0;x.traverse(o=>{if(!(o instanceof T.Mesh))return;const mat=Array.isArray(o.material)?o.material[0]:o.material;const e=(mat as T.MeshStandardMaterial).emissive;if(e){const r=e.r,g=e.g,b=e.b;if(r>=g*1.3&&r>=b*1.3){tz+=o.position.z;tn++}else if(r+g+b>.06){hz+=o.position.z;hn++}}});x.userData.tail=tn?tz/tn:0;x.userData.head=hn?hz/hn:0};if(vid==='coupe'){glbTextures.push(...m.textures);for(let i=pCar.children.length-1;i>=0;i--)pCar.remove(pCar.children[i]);pCar.add(m.group);glbMark(car);garage.coupe={group:car,wheels:m.wheels,tailMat:m.tailMat,textures:m.textures}}else{const g=carGroups[vid];if(active&&vid===selected&&(mode==='car'||mode==='foot')){g.position.copy(driven.position);g.rotation.set(0,driven.rotation.y,0)}g.add(m.group);glbMark(g);garage[vid]={group:g,wheels:m.wheels,tailMat:m.tailMat,textures:m.textures};glbTextures.push(...m.textures);if(active&&vid===selected&&mode==='car'){driven=g;applyCharacter();emit()}}renderVehicles();setLoad()})}
  for(const [id,url]of Object.entries(BIKE_GLB)){void loadBikeModelMulti(url).then(m=>{if(disposed||!m||bikeGarage[id])return;bikeGarage[id]=m;glbTextures.push(...m.textures);if(selected===id)setBikeModel(id);else renderVehicles();setLoad()})}
  void loadBikeModel('/bmw_s1000rr.glb').then(m=>{if(disposed||bmwGroup||!m)return;bmwGroup=m.group;glbTextures.push(...m.textures);if(selected==='bike')mountBike(m.group);else renderVehicles();setLoad()});
 const keys:Record<string,boolean>={};let active=false,paused=false,disposed=false,muted=false,yaw=0,vx=0,vz=0,steer=0,score=0,combo=0,driftGrace=0,frame=0,clock=0,raf=0,accum=0;let mapOpen=false,pausedWithMap=false,style:DriveStyle='standard',lastEarned=0,mapPausing=false,scoreQ=0,inDrift=false,sessQ=0,sessFlips=0,seriesMult=1,lastLat=0,lastQ=0,sportMode=false;
 let mode:TravelMode='car',driven=car,cameraOrbit=0,camOff=0,walkPhase=0,notice='',noticeUntil=0,dragging=false,lastPointerX=0,bikeLean=0,camRoll=0,roll=0,pitch=0,slopeRoll=0,slopePitch=0,frontVis=0,rearVis=0,counterVis=0,lat=0,rollVel=0,pitchVel=0,rollT=0,pitchT=0,driftingNow=false,npcHit=0;
  const eYaw=new T.Euler(),eRoll=new T.Euler(),ePitch=new T.Euler(),eSlopeP=new T.Euler(),eSlopeR=new T.Euler(),eLean=new T.Euler(),qRoll=new T.Quaternion(),qPitch=new T.Quaternion(),qSlopeP=new T.Quaternion(),qSlopeR=new T.Quaternion(),qLean=new T.Quaternion();
  const RK=(2*Math.PI*1.4)**2,RD=2*.93*2*Math.PI*1.4,PK=(2*Math.PI*1.5)**2,PD=2*1*2*Math.PI*1.5,RKR=(2*Math.PI*4.5)**2,RDR=2*2*Math.PI*4.5,PKR=(2*Math.PI*3.8)**2,PDR=2*2*Math.PI*3.8;
  let audio:AudioContext|null=null,osc:OscillatorNode|null=null,gain:GainNode|null=null;
 const focus=()=>mode==='foot'?character.group:driven;
 const pose=(v:T.Group)=>({x:v.position.x,z:v.position.z,yaw:v.rotation.y});
 function ensureAudio(){if(!audio){audio=new AudioContext();osc=audio.createOscillator();osc.type='sawtooth';gain=audio.createGain();gain.gain.value=0;const filter=audio.createBiquadFilter();filter.type='lowpass';filter.frequency.value=240;osc.connect(filter).connect(gain).connect(audio.destination);osc.start()}void audio.resume()}
function hint(){if(clock<noticeUntil)return notice;const bikeName=()=>CAR_NAMES[isBikeId(selected)?selected:'coupe'];if(interior)return 'E · Step out';if(mode!=='foot')return 'E · Get out of '+(mode==='bike'?bikeName():carName());if(doorNear(character.group.position.x,character.group.position.z))return 'E · Step inside';const nearest=nearestVehicle({x:character.group.position.x,z:character.group.position.z},pose(activeCar()),pose(motorbike.group));if(nearest)return 'E · '+(nearest==='bike'?'Ride the '+bikeName():'Enter '+carName());return 'Walk to a vehicle · R to regroup'}
  const doorNear=(x:number,z:number)=>{let d:InteriorDoor|null=null,dist=Infinity;for(const q of interiorDoors){const qd=(x-q.outX)**2+(z-q.outZ)**2;if(qd<dist){dist=qd;d=q}}return dist<7.8?d:null};
  let interiorWasGen=false;
  function enterInterior(d:InteriorDoor){interior=d;interiorWasGen=genWorld!==null&&genRoot.visible;npc?.despawn();coast.visible=false;parking.group.visible=false;raceway.group.visible=false;for(const[,t]of towns)t.group.visible=false;genRoot.visible=false;for(const g of Object.values(carGroups))g.visible=false;motorbike.group.visible=false;interiorRoom.enter(d);mode='foot';vx=vz=steer=combo=0;cameraOrbit=d.inYaw;yaw=d.inYaw;character.group.position.set(d.inX,d.floor,d.inZ);for(const k in keys)keys[k]=false;applyCharacter();emit();updateCamera(1)}
  function leaveInterior(){const d=interior;if(!d)return;interiorRoom.leave();interior=null;genRoot.visible=interiorWasGen;applyWorldVisibility();renderVehicles();character.group.position.set(d.outX,d.floor,d.outZ);cameraOrbit=d.outYaw;yaw=d.outYaw;vx=vz=steer=0;for(const k in keys)keys[k]=false;if(npc){npc.respawn(d.outX,d.outZ);npc.spawnWild(d.outX,d.outZ,isBikeId(selected))}applyCharacter();emit();updateCamera(1)}
  function cycleStyle(){style=style==='drift'?'standard':'drift';notice=style==='drift'?'DRIFT MODE — stay loose':'STANDARD MODE — full grip';noticeUntil=clock+1800;emit()}
  function bankScore(){finalizeDrift();const n=scoreQ>=RATE?Math.floor(scoreQ/RATE):0;scoreQ-=n*RATE;if(n>0){addCash(n);lastEarned=n}score=0;combo=0;emit()}
  function finalizeDrift(){if(!inDrift)return;inDrift=false;if(sessFlips>0)scoreQ+=sessQ;else scoreQ+=Math.floor(sessQ*.1/RATE)*RATE;sessQ=0;sessFlips=0;seriesMult=1;lastLat=0}
  function emit(drifting=false,angle=0){const f=focus();const carPose=activeCar();const earned=lastEarned;lastEarned=0;onHUD({speed:Math.hypot(vx,vz)*3.6,score,combo,angle,drifting,x:f.position.x,z:f.position.z,yaw,mode,hint:hint(),carX:carPose.position.x,carZ:carPose.position.z,bikeX:motorbike.group.position.x,bikeZ:motorbike.group.position.z,style,earned,loading:loadingCar(),sport:mapId==='raceway'&&sportMode,interior:!!interior});(window as Window & {__hud?:unknown}).__hud={speed:Math.hypot(vx,vz)*3.6,score,combo,carX:carPose.position.x,carZ:carPose.position.z,carY:carPose.position.y,x:f.position.x,z:f.position.z,yaw:carPose.rotation.y,mode,vehicle:selected,hint:hint(),earned,loading:loadingCar(),sport:mapId==='raceway'&&sportMode,camOff,interior:!!interior,seat:mode!=='foot'?{fx:character.group.position.x,fy:character.group.position.y,fz:character.group.position.z,drvX:driven.position.x,drvZ:driven.position.z,drvY:driven.position.y,drvYaw:driven.rotation.y,lean:bikeLean,scale:character.group.scale.x,roofY:mode==='car'?new T.Box3().setFromObject(driven).max.y:undefined,mode,rq:[character.group.quaternion.x,character.group.quaternion.y,character.group.quaternion.z,character.group.quaternion.w],dq:[driven.quaternion.x,driven.quaternion.y,driven.quaternion.z,driven.quaternion.w],tail:typeof driven.userData.tail==='number'&&driven.userData.tail!==0?driven.userData.tail:undefined,head:typeof driven.userData.head==='number'&&driven.userData.head!==0?driven.userData.head:undefined}:undefined};(window as Window & {__sus?:unknown}).__sus={roll,pitch,camRoll,slopeRoll,slopePitch,wheelFront:frontVis,wheelRear:rearVis,countersteer:counterVis,steer,lat,rollVel,pitchVel,rollTarget:rollT,pitchTarget:pitchT,stable:Math.abs(rollT-roll)<.01&&Math.abs(pitchT-pitch)<.01&&Math.abs(rollVel)<.05&&Math.abs(pitchVel)<.05,q:lastQ,flips:sessFlips,mult:seriesMult,slip:angle,yaw:carPose.rotation.y,mode}}
  const probe=(window as Window & {__probe?:unknown}).__probe=(x:number,z:number,top=140)=>{try{const r=new T.Raycaster(new T.Vector3(x,top,z),new T.Vector3(0,-1,0),0,top+50);const targets=(genActive()?[genRoot]:[]).concat(raceway.group.visible?[raceway.group]:[]).concat(town&&town.group.parent?[town.group]:[]);const hits=r.intersectObjects(targets,true);return hits.slice(0,4).map(h=>({d:Math.round(h.distance*10)/10}))}catch(e){return[{'e':1}]}};
const mm=(window as Window & {__mm?:unknown}).__mm=(x:number,z:number)=>genActive()?(genWorld!.mode==='sport'&&ring?Math.round(ring.height(x,z)*100)/100:Math.round((genEntryAt(x,z)?.town.height(x,z)??worldHeight(x,z,genWorld!.seed))*100)/100):town?Math.round(town.height(x,z)*100)/100:null;
  (window as Window & {__doors?:unknown}).__doors=()=>interiorDoors;
  (window as Window & {__foot?:unknown}).__foot=(x:number,z:number,yaw=0)=>{mode='foot';cameraOrbit=yaw;vx=vz=steer=0;character.group.position.set(x,groundY(x,z),z);for(const k in keys)keys[k]=false;applyCharacter();emit();updateCamera(1)};
  type GenWorld={mode:'saved'|'infinite'|'sport';seed:number;id:string;title:string;data?:TownData;params:GenOptions};
  let genWorld:null|{mode:'saved'|'infinite'|'sport';seed:number;id:string;params:GenOptions;ccx:number;ccz:number}=null;
  let ring:null|RingHandle=null;
  const genTowns=new Map<string,{x:number;z:number;town:ReturnType<typeof createTown>}>();
  let genSpawn:{x:number;z:number;yaw:number}|null=null;
  let genQueue:(()=>void)[]=[],genBuilding=false,genQueuedKeys=new Set<string>();
  const genActive=()=>genWorld!==null&&genRoot.visible;
  function genEntryAt(x:number,z:number){for(const e of genTowns.values()){const b=e.town.data.bounds;if(x>=b[0]&&x<b[2]&&z>=b[1]&&z<b[3])return e}return null}
  function disposeChunkTown(t:{x:number;z:number;town:ReturnType<typeof createTown>}){t.town.group.parent?.remove(t.town.group);t.town.group.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();const ms=Array.isArray(o.material)?o.material:[o.material];ms.forEach(m=>m.dispose())}});t.town.textures.forEach(tex=>tex.dispose())}
  function teardownGen(){ring?.destroy();ring=null;genQueue=[];genBuilding=false;genQueuedKeys.clear();for(const e of genTowns.values())disposeChunkTown(e);genTowns.clear();genSpawn=null;if(genWorld)genWorld=null;genRoot.visible=false;applyWorldVisibility()}
  function drainGen(){if(genBuilding)return;genBuilding=true;setTimeout(function run(){const f=genQueue.shift();if(f){try{f()}catch(e){console.warn(e)}}if(genQueue.length)setTimeout(run,0);else{genBuilding=false;if(active)emit()}},0)}
  function ensureChunk(seed:number,cx:number,cz:number){const k=chunkKey(cx,cz);if(genTowns.has(k)||genQueuedKeys.has(k))return;genQueuedKeys.add(k);genQueue.push(()=>{if(disposed||!genWorld||genWorld.seed!==seed||!genRoot.visible){genQueuedKeys.delete(k);return}const data=generateChunk(seed,cx,cz,{flat:!!genWorld.params.flat,roadsScale:genWorld.params.roadsScale});if(disposed||!genWorld||genWorld.seed!==seed||!genRoot.visible){genQueuedKeys.delete(k);return}const t=createTown(data);if(!genRoot.visible){genQueuedKeys.delete(k);return}genRoot.add(t.group);genTowns.set(chunkKey(cx,cz),{x:cx,z:cz,town:t});genQueuedKeys.delete(k)});drainGen()}
  function chunkCenter(x:number,z:number){return{x:Math.floor(x/CHUNK),z:Math.floor(z/CHUNK)}}
  function neededKeys(cx:number,cz:number,radius:number){const set=new Set<string>();for(let dx=-radius;dx<=radius;dx++)for(let dz=-radius;dz<=radius;dz++){if(Math.abs(dx)+Math.abs(dz)>radius)continue;set.add(chunkKey(cx+dx,cz+dz))}return set}
  function updateGenArea(){const g=genWorld;if(!g||g.mode!=='infinite'||!active)return;const f=focus(),c=chunkCenter(f.position.x,f.position.z);if(g.ccx===c.x&&g.ccz===c.z)return;g.ccx=c.x;g.ccz=c.z;const needed=neededKeys(c.x,c.z,2);for(const[k,e]of[...genTowns]){if(!needed.has(k)){disposeChunkTown(e);genTowns.delete(k)}}for(let dx=-2;dx<=2;dx++)for(let dz=-2;dz<=2;dz++){if(Math.abs(dx)+Math.abs(dz)>2)continue;ensureChunk(g.seed,c.x+dx,c.z+dz)}}
  function applyWorldVisibility(){const g=genWorld!==null&&genRoot.visible;coast.visible=!g&&mapId==='coast';parking.group.visible=!g&&mapId==='costco';raceway.group.visible=!g&&mapId==='raceway';for(const[mid,t]of towns)t.group.visible=!g&&mid===mapId}
  async function selectGenWorld(w:GenWorld){if(interior)leaveInterior();teardownGen();npc?.destroy();npc=null;if(w.mode==='sport'){ring=createRing({scene,seed:w.seed});genWorld={mode:'sport',seed:w.seed,id:w.id,params:w.params,ccx:0,ccz:0};genRoot.add(ring.group);genSpawn=ring.spawnPose()}else if(w.mode==='infinite'){genWorld={mode:'infinite',seed:w.seed,id:w.id,params:w.params,ccx:0,ccz:0};const c0=generateChunk(w.seed,0,0,{flat:!!w.params.flat,roadsScale:w.params.roadsScale});if(disposed||!genWorld)return;const t0=createTown(c0);genRoot.add(t0.group);genTowns.set(chunkKey(0,0),{x:0,z:0,town:t0});for(let dx=-2;dx<=2;dx++)for(let dz=-2;dz<=2;dz++){if(Math.abs(dx)+Math.abs(dz)>2)continue;ensureChunk(w.seed,dx,dz)}let gs={x:CHUNK/2,z:SPACING/2,yaw:Math.PI},gd=1e9;for(const r of c0.roads){for(let i=0;i<r.p.length-1;i++){const ax=r.p[i][0],az=r.p[i][1],bx=r.p[i+1][0],bz=r.p[i+1][1],ddx=bx-ax,ddz=bz-az,l2=ddx*ddx+ddz*ddz;if(l2<.01)continue;const tt=Math.max(0,Math.min(1,((CHUNK/2-ax)*ddx+(SPACING/2-az)*ddz)/l2));const px=ax+tt*ddx,pz=az+tt*ddz,d2=(px-CHUNK/2)**2+(pz-SPACING/2)**2;if(d2<gd){gd=d2;gs={x:px,z:pz,yaw:Math.atan2(-ddx,-ddz)}}}}genSpawn=gs}else{let data=w.data;if(!data)data=await loadGenMapData(w.id);if(disposed||genWorld||genRoot.visible)return;genWorld={mode:'saved',seed:w.seed,id:w.id,params:w.params,ccx:0,ccz:0};const t=createTown(data);genRoot.add(t.group);genTowns.set(chunkKey(0,0),{x:0,z:0,town:t});genSpawn={x:data.spawn.x,z:data.spawn.z,yaw:data.spawn.yaw}}genRoot.visible=true;ring?.reset();(scene.fog as T.FogExp2).density=.0008;mapId='coast';applyWorldVisibility();const gt=[...genTowns.values()][0]?.town;if(gt){npc=createNpc({id:'gen_'+w.seed,roads:gt.data.roads,areas:gt.data.areas,bounds:gt.data.bounds,height:(x,z)=>gt.height(x,z),scene,low:LOW});interiorDoors=planInteriors(gt.data,(x,z)=>gt.height(x,z))}else interiorDoors=[];bankScore();skids.forEach(s=>s.visible=false);smoke.forEach(p=>{p.life=0;p.s.material.opacity=0});reset();emit()}
  function groundCollision(x:number,z:number,dx:number,dz:number,previous:[number,number],radius:number){if(interior){const d=interior;const du=(x-d.outX)*d.ux+(z-d.outZ)*d.uz,dn=(x-d.outX)*d.nx+(z-d.outZ)*d.nz,du2=T.MathUtils.clamp(du,d.duMin,d.duMax),dn2=T.MathUtils.clamp(dn,d.dnMin,d.dnMax);let hit=false;if(du2!==du){dx=0;hit=true}if(dn2!==dn){dz=0;hit=true}return{x:d.outX+du2*d.ux+dn2*d.nx,z:d.outZ+du2*d.uz+dn2*d.nz,vx:dx,vz:dz,hit}}if(genActive()){if(genWorld!.mode==='sport'&&ring)return ring.collide(x,z,dx,dz,previous,radius);const e=genEntryAt(x,z);return e?e.town.collide(x,z,dx,dz,previous,radius):{x,z,vx:dx,vz:dz,hit:false}}if(TOWN_MAPS.has(mapId)&&town)return town.collide(x,z,dx,dz,previous,radius);if(mapId==='costco')return parkingCollision(x,z,dx,dz,parking.obstacles,radius);if(mapId==='raceway')return raceway.collide(x,z,dx,dz,previous,radius);let nearest=0,distance=Infinity;for(let i=0;i<400;i++){const d=(x-samples[i].x)**2+(z-samples[i].z)**2;if(d<distance){distance=d;nearest=i}}const off=Math.sqrt(distance);let hit=false;if(off>16){const p=samples[nearest],nx=(x-p.x)/off,nz=(z-p.z)/off;x=p.x+nx*16;z=p.z+nz*16;const out=dx*nx+dz*nz;if(out>0){dx-=nx*out*1.4;dz-=nz*out*1.4}hit=true}return{x,z,vx:dx,vz:dz,hit}}
  const groundY=(x:number,z:number)=>interior?interior.floor:genActive()?(genWorld!.mode==='sport'&&ring?ring.height(x,z):(genEntryAt(x,z)?.town.height(x,z)??worldHeight(x,z,genWorld!.seed))):mapId==='raceway'?raceway.height(x,z):town?town.height(x,z):0;
 function applyCharacter(moving=0){if(mode==='foot'){character.group.scale.setScalar(.9);character.group.rotation.set(0,yaw,0);character.pose('foot',walkPhase,moving)}else if(mode==='car'){const local=new T.Vector3(-.38,-.08,.13);local.applyAxisAngle(new T.Vector3(0,1,0),yaw);character.group.position.copy(driven.position).add(local);character.group.quaternion.copy(driven.quaternion);character.group.scale.setScalar(.68);character.pose(mode,0,0)}else{const leanComp=bikeLean*.18;const local=new T.Vector3(leanComp,.42,.28);local.applyAxisAngle(new T.Vector3(0,1,0),yaw);character.group.position.copy(driven.position).add(local);character.group.quaternion.copy(driven.quaternion);character.group.scale.setScalar(1);character.pose(mode,0,0)}}
  function reset(){if(interior)leaveInterior();const sp=genActive()?genSpawn:(mapId==='wurzburg'?WURZBURG_SPAWN:(mapId==='raceway'?raceway.spawnPose():(town?.data.spawn))),hasSpawn=!!sp,p=hasSpawn?new T.Vector3(sp.x,groundY(sp.x,sp.z),sp.z):mapId==='costco'?new T.Vector3(0,0,75):curve.getPointAt(.03),t=hasSpawn?new T.Vector3(-Math.sin(sp.yaw),0,-Math.cos(sp.yaw)):mapId==='costco'?new T.Vector3(0,0,-1):curve.getTangentAt(.03);const spawnY=groundY(p.x,p.z);  if(npc){if(!paused){npc.respawn(p.x,p.z);npc.spawnWild(p.x,p.z,isBikeId(selected))}else npc.despawn()}mode=isBikeId(selected)?'bike':'car';if(mode==='bike'){motorbike.group.position.set(p.x,spawnY,p.z);yaw=Math.atan2(-t.x,-t.z);motorbike.group.rotation.set(0,yaw,-.09);driven=motorbike.group;const cOff=new T.Vector3(3.5,0,-4).applyAxisAngle(new T.Vector3(0,1,0),yaw);const cg=activeCar();cg.position.set(p.x+cOff.x,spawnY,p.z+cOff.z);cg.rotation.set(0,yaw,0)}else{const cg=activeCar();cg.position.set(p.x,spawnY,p.z);yaw=Math.atan2(-t.x,-t.z);cg.rotation.set(0,yaw,0);driven=cg;const bOff=new T.Vector3(3.5,0,-4).applyAxisAngle(new T.Vector3(0,1,0),yaw);motorbike.group.position.copy(cg.position).add(new T.Vector3(bOff.x,spawnY-cg.position.y,bOff.z));motorbike.group.rotation.set(0,yaw,-.09)}cameraOrbit=yaw;camOff=0;vx=vz=steer=combo=driftGrace=accum=0;roll=pitch=rollVel=pitchVel=rollT=pitchT=slopeRoll=slopePitch=frontVis=rearVis=counterVis=0;bikeLean=0;noticeUntil=0;finalizeDrift();for(const k in keys)keys[k]=false;applyCharacter();emit();updateCamera(1)}
 function updateCamera(dt:number){const f=focus();const heading=mode==='foot'?cameraOrbit:yaw+camOff,forward=new T.Vector3(-Math.sin(heading),0,-Math.cos(heading));let target:T.Vector3;if(!active){target=f.position.clone().add(new T.Vector3(-9,4.7,9));camera.position.lerp(target,Math.min(1,dt*2));camera.lookAt(f.position.clone().add(new T.Vector3(-3.2,.7,0)))}else{target=f.position.clone().addScaledVector(forward,interior?-2.6:(mode==='foot'?-4.7:mode==='bike'?-5.2:-6.4-Math.min(2,Math.hypot(vx,vz)*.05)));target.y=f.position.y+(interior?2.2:(mode==='foot'?2.9:mode==='bike'?3.2:4.3));camera.position.lerp(target,1-Math.exp(-dt*5));camera.lookAt(f.position.clone().addScaledVector(forward,mode==='foot'?1:3.4).add(new T.Vector3(0,mode==='foot'?1.2:.9,0)))}if(genActive()&&genWorld!.mode==='saved'){const b=genTowns.get(chunkKey(0,0))?.town.data.bounds;if(b){const m=48;camera.position.x=T.MathUtils.clamp(camera.position.x,b[0]+m,b[2]-m);camera.position.z=T.MathUtils.clamp(camera.position.z,b[1]+m,b[3]-m)}}else if(TOWN_MAPS.has(mapId)&&town){const b=town.data.bounds,m=48;camera.position.x=T.MathUtils.clamp(camera.position.x,b[0]+m,b[2]-m);camera.position.z=T.MathUtils.clamp(camera.position.z,b[1]+m,b[3]-m)}if(interior){const dd=interior,cu=(camera.position.x-dd.outX)*dd.ux+(camera.position.z-dd.outZ)*dd.uz,cn=(camera.position.x-dd.outX)*dd.nx+(camera.position.z-dd.outZ)*dd.nz;const cu2=T.MathUtils.clamp(cu,dd.duMin+.55,dd.duMax-.55),cn2=T.MathUtils.clamp(cn,dd.dnMin+.55,dd.dnMax-.55);camera.position.x=dd.outX+cu2*dd.ux+cn2*dd.nx;camera.position.z=dd.outZ+cu2*dd.uz+cn2*dd.nz;camera.position.y=T.MathUtils.clamp(camera.position.y,dd.floor+.4,dd.floor+3.5)}if(mode==='bike'){camRoll+=(bikeLean*.5-camRoll)*Math.min(1,dt*4)}else{camRoll+=(roll*.3-camRoll)*Math.min(1,dt*6.5)}camera.rotateZ(camRoll);const fov=mode==='foot'?55:48+Math.min(9,Math.hypot(vx,vz)*.08);camera.fov+=(fov-camera.fov)*Math.min(1,dt*3);camera.updateProjectionMatrix()}
 function avoidVehicle(x:number,z:number,v:T.Group,width:number,length:number){const local=new T.Vector3(x-v.position.x,0,z-v.position.z).applyAxisAngle(new T.Vector3(0,1,0),-v.rotation.y);if(Math.abs(local.x)<width&&Math.abs(local.z)<length){if(width-Math.abs(local.x)<length-Math.abs(local.z))local.x=Math.sign(local.x||1)*width;else local.z=Math.sign(local.z||1)*length;local.applyAxisAngle(new T.Vector3(0,1,0),v.rotation.y).add(v.position);return[local.x,local.z] as [number,number]}return[x,z] as [number,number]}
  function walking(dt:number){const forward=(keys.W?1:0)-(keys.S?1:0),strafe=(keys.D?1:0)-(keys.A?1:0);const length=Math.hypot(forward,strafe),speed=keys.Shift?6.4:3.1;vx=length?(-Math.sin(cameraOrbit)*forward+Math.cos(cameraOrbit)*strafe)*speed/length:0;vz=length?(-Math.cos(cameraOrbit)*forward-Math.sin(cameraOrbit)*strafe)*speed/length:0;const f=character.group,previous:[number,number]=[f.position.x,f.position.z];const c=groundCollision(f.position.x+vx*dt,f.position.z+vz*dt,vx,vz,previous,.4);let pos=avoidVehicle(c.x,c.z,activeCar(),1.6,3.0);pos=avoidVehicle(pos[0],pos[1],motorbike.group,.9,1.85);f.position.set(pos[0],groundY(pos[0],pos[1]),pos[1]);if(length){const desired=Math.atan2(-vx,-vz);yaw+=Math.atan2(Math.sin(desired-yaw),Math.cos(desired-yaw))*Math.min(1,dt*12)}walkPhase+=dt*(keys.Shift?12:8)*Math.min(length,1);applyCharacter(Math.min(length,1));if(frame%6===0)emit();if(gain&&audio)gain.gain.setTargetAtTime(0,audio.currentTime,.1)}
  function interact(){if(!active||paused)return;if(interior){leaveInterior();return}if(mode==='foot'){const door=doorNear(character.group.position.x,character.group.position.z);if(door){enterInterior(door);return}const nearest=nearestVehicle({x:character.group.position.x,z:character.group.position.z},pose(activeCar()),pose(motorbike.group));if(!nearest){notice='Get closer to a vehicle';noticeUntil=clock+2000;emit();return}mode=nearest;driven=(mode==='car'?activeCar():motorbike.group)??car;yaw=driven.rotation.y;vx=vz=steer=0;camOff=0;bikeLean=0;applyCharacter();emit();return}if(Math.hypot(vx,vz)>5){notice='Slow down to exit';noticeUntil=clock+1800;emit();return}const candidates=exitCandidates(pose(driven));let safe:[number,number]|null=null;for(const p of candidates){const c=groundCollision(p[0],p[1],0,0,[driven.position.x,driven.position.z],.4);if(!c.hit){safe=p;break}}if(!safe){notice='Move to an open spot to exit';noticeUntil=clock+2000;emit();return}if(mode==='bike'){motorbike.group.rotation.z=-.09;const bm=bikeGarage[selected];if(bm?.tailMat)bm.tailMat.emissiveIntensity=2}driven.position.y=groundY(driven.position.x,driven.position.z);mode='foot';vx=vz=steer=combo=0;cameraOrbit=yaw;camOff=0;character.group.position.set(safe[0],groundY(safe[0],safe[1]),safe[1]);for(const k in keys)keys[k]=false;applyCharacter();emit()}
 function physics(dt:number){if(mode==='foot'){walking(dt);return}const speed=Math.hypot(vx,vz),fx=-Math.sin(yaw),fz=-Math.cos(yaw),rx=Math.cos(yaw),rz=-Math.sin(yaw);let longitudinal=vx*fx+vz*fz,lateral=vx*rx+vz*rz;const throttle=(keys.W?1:0)-(keys.S?1:0);const turn=(keys.A?1:0)-(keys.D?1:0),brake=!!keys.SPACE,biking=mode==='bike';const sp=(mapId==='raceway'&&sportMode?2:1);
steer+=(turn-steer)*(1-Math.exp(-dt*9));const slip=brake&&speed>5;let slipAngle=0;
if(style==='drift'){if(biking){longitudinal+=throttle*(throttle*longitudinal<0?50*sp:34*sp)*dt;longitudinal*=Math.exp(-(brake?.48:.14+Math.abs(longitudinal)*.0007)*dt);longitudinal=T.MathUtils.clamp(longitudinal,-9*sp,277.78*sp);const grip=slip?1.8:3.6;lateral*=Math.exp(-grip*dt);slipAngle=Math.abs(Math.atan2(lateral,Math.abs(longitudinal)))*180/Math.PI;yaw+=steer*Math.min(Math.abs(longitudinal)/8,1)*1.5*(longitudinal<0?-1:1)*dt*(slip?1.25:1);yaw+=lateral*.28*Math.max(0,1-slipAngle/70)*dt}else{const h0=HANDLING[selected],h=sp>1?{...h0,accel:h0.accel*sp,rev:h0.rev*sp,max:h0.max*sp,maxRev:h0.maxRev*sp,dragBase:h0.dragBase*sp}:h0;longitudinal+=throttle*(throttle*longitudinal<0?h.rev:h.accel)*dt;longitudinal*=Math.exp(-(brake?h.brakeDrag:h.dragBase+Math.abs(longitudinal)*h.dragLin)*dt);longitudinal=T.MathUtils.clamp(longitudinal,h.maxRev,h.max);const grip=slip?h.driftGripSlip:Math.abs(steer)>.2&&speed>12?h.driftGripSteer:h.driftGrip;lateral*=Math.exp(-grip*dt);slipAngle=Math.abs(Math.atan2(lateral,Math.abs(longitudinal)))*180/Math.PI;yaw+=steer*Math.min(Math.abs(longitudinal)/8,1)*h.steer*(longitudinal<0?-1:1)*dt;yaw+=lateral*h.latYaw*Math.max(0,1-slipAngle/70)*dt}}
else{if(biking){longitudinal+=throttle*(throttle*longitudinal<0?48*sp:29*sp)*dt;longitudinal*=Math.exp(-(brake?1.2:.16+speed*.0008)*dt);longitudinal=T.MathUtils.clamp(longitudinal,-6*sp,72*sp);const grip=brake?2:6;lateral*=Math.exp(-grip*dt);slipAngle=Math.abs(Math.atan2(lateral,Math.abs(longitudinal)))*180/Math.PI;yaw+=steer*Math.min(Math.abs(longitudinal)/8,1)*(.95+Math.min(speed,65)*.004)*(longitudinal<0?-1:1)*dt}else{const h0=HANDLING[selected],h=sp>1?{...h0,accel:h0.accel*sp,rev:h0.rev*sp,max:h0.max*sp,maxRev:h0.maxRev*sp,dragBase:h0.dragBase*sp}:h0;longitudinal+=throttle*(throttle*longitudinal<0?h.rev:h.accel)*dt;longitudinal*=Math.exp(-(brake?h.brakeDrag:h.dragBase+speed*h.dragLin)*dt);longitudinal=T.MathUtils.clamp(longitudinal,h.maxRev,h.max);const grip=slip?h.gripSlip:Math.abs(steer)>.2&&speed>12?h.gripSteer:h.grip;lateral*=Math.exp(-grip*dt);slipAngle=Math.abs(Math.atan2(lateral,Math.abs(longitudinal)))*180/Math.PI;yaw+=steer*Math.min(Math.abs(longitudinal)/8,1)*(.95+Math.min(speed,65)*h.steerSpeed)*(longitudinal<0?-1:1)*dt*(slip?1.3:1)}}
  const previous:[number,number]=[driven.position.x,driven.position.z];vx=fx*longitudinal+rx*lateral;vz=fz*longitudinal+rz*lateral;const c=groundCollision(driven.position.x+vx*dt,driven.position.z+vz*dt,vx,vz,previous,biking?.9:2.3);driven.position.x=c.x;driven.position.z=c.z;vx=c.vx;vz=c.vz;if(c.hit)combo=0;driven.position.y=groundY(driven.position.x,driven.position.z);
  const other=biking?garage[selected]?.group??car:motorbike.group;const separation=driven.position.distanceTo(other.position);if(separation<(biking?2.4:2.3)&&separation>.001){const n=driven.position.clone().sub(other.position).normalize();driven.position.copy(other.position).addScaledVector(n,2.45);const into=vx*n.x+vz*n.z;if(into<0){vx-=1.2*into*n.x;vz-=1.2*into*n.z}combo=0}const track=biking?.4:1.02,wb=biking?.7:1.45,sa=groundY(driven.position.x+rx*track+fx*wb,driven.position.z+rz*track+fz*wb),sb=groundY(driven.position.x-rx*track+fx*wb,driven.position.z-rz*track+fz*wb),sc=groundY(driven.position.x+rx*track-fx*wb,driven.position.z+rz*track-fz*wb),sd=groundY(driven.position.x-rx*track-fx*wb,driven.position.z-rz*track-fz*wb),ssk=1-Math.exp(-dt*SLOPE_K);slopeRoll+=(Math.atan2(-(sa+sc-sb-sd),4*track)-slopeRoll)*ssk;slopePitch+=(Math.atan2(sa+sb-sc-sd,4*wb)-slopePitch)*ssk;
const drifting=!c.hit&&speed>7&&(slipAngle>(style==='drift'?7:9)||(slip&&Math.abs(steer)>.2));driftingNow=drifting;if(drifting){const points=dt*speed*(1+Math.min(slipAngle,60)/15);score+=points;combo+=points;driftGrace=1;if(!inDrift){inDrift=true;sessQ=0;sessFlips=0;seriesMult=1;lastLat=0}const sq=T.MathUtils.clamp((slipAngle-Q_MIN)/Q_RANGE,0,1)*T.MathUtils.clamp(speed/Q_SPEED,.4,1);lastQ=sq;sessQ+=dt*speed*sq*seriesMult*.3;if(Math.abs(lateral)>1.5){const s=lateral<0?-1:1;if(lastLat!==0&&s!==lastLat){sessFlips++;seriesMult=Math.min(MULT_MAX,seriesMult*FLIP_MULT);sessQ+=FLIP_PTS*(.5+.5*sq)*Math.min(1,speed/20)}lastLat=s}}else{driftGrace-=dt;if(driftGrace<=0){combo=0;finalizeDrift()}}
  if(biking){const slipNorm=T.MathUtils.clamp(slipAngle/52,0,1);const lean=T.MathUtils.clamp(steer*(1-slipNorm)*Math.min(1,speed/30)*.95-lateral*.16*slipNorm,-.85,.85);bikeLean=lean;eYaw.set(0,yaw,0);eSlopeP.set(slopePitch,0,0);eSlopeR.set(0,0,slopeRoll);eLean.set(0,0,lean*Math.min(1,.4+speed*.014));motorbike.group.quaternion.setFromEuler(eYaw).multiply(qSlopeP.setFromEuler(eSlopeP)).multiply(qSlopeR.setFromEuler(eSlopeR)).multiply(qLean.setFromEuler(eLean));const bikeModel=bikeGarage[isBikeId(selected)?selected:'bike'];if(bikeModel?.tailMat)bikeModel.tailMat.emissiveIntensity=brake?7:2;else if(!glbBike)(motorbike.tailLight.material as T.MeshStandardMaterial).emissiveIntensity=brake?5:2;bikeModel?.wheels.forEach(w=>w.rotation.x+=longitudinal*dt/.28);motorbike.group.scale.setScalar(VEHICLE_SCALE)}else{const sp2=Math.hypot(vx,vz),rt=T.MathUtils.clamp(-lateral*Math.min(sp2,120)*.0042,-.13,.13),pt=T.MathUtils.clamp((throttle>0?Math.min(1,Math.max(0,longitudinal)*.004):0)*.055-(brake||throttle<0&&sp2>6?1:0)*.06,-.06,.06);const level=(Math.abs(steer)<.02||turn===0)&&Math.abs(lateral)<.5&&sp2>2;if(level){rollT=0;rollVel=T.MathUtils.clamp(rollVel+(RKR*(0-roll)-RDR*rollVel)*dt,-1.5,1.5)}else{rollT=rt;rollVel=T.MathUtils.clamp(rollVel+(RK*(rt-roll)-RD*rollVel)*dt,-1.5,1.5)}roll+=rollVel*dt;if(level&&!keys.W&&!keys.S&&!keys.SPACE){pitchT=0;pitchVel=T.MathUtils.clamp(pitchVel+(PKR*(0-pitch)-PDR*pitchVel)*dt,-1.5,1.5)}else{pitchT=pt;pitchVel=T.MathUtils.clamp(pitchVel+(PK*(pt-pitch)-PD*pitchVel)*dt,-1.5,1.5)}pitch+=pitchVel*dt;eYaw.set(0,yaw,0);eSlopeP.set(slopePitch,0,0);eSlopeR.set(0,0,slopeRoll);eRoll.set(0,0,roll);ePitch.set(pitch,0,0);driven.quaternion.setFromEuler(eYaw).multiply(qSlopeP.setFromEuler(eSlopeP)).multiply(qSlopeR.setFromEuler(eSlopeR)).multiply(qRoll.setFromEuler(eRoll)).multiply(qPitch.setFromEuler(ePitch));const g=garage[selected];if(g?.tailMat)g.tailMat.emissiveIntensity=brake||keys.S?7:2;const csT=drifting?-Math.sign(lateral)*Math.min(Math.abs(lateral)*CS_K,CS_MAX):0;counterVis+=(csT-counterVis)*Math.min(1,dt*8);const fT=-(steer*VIS_STEER+counterVis);frontVis+=(fT-frontVis)*Math.min(1,dt*10);const rCap=throttle>0.5&&drifting?REAR_DRIFT:REAR_BASE;rearVis+=(Math.sign(lateral)*Math.min(Math.abs(lateral)*REAR_K,rCap)-rearVis)*Math.min(1,dt*6);(g?.wheels??pCar.children.filter(c=>c instanceof T.Group&&c.position.y<1&&Math.abs(c.position.x)>0.8)).forEach((w,i)=>{w.rotation.y=i%2===0?frontVis:rearVis;if(w.userData.glb)w.rotation.x+=longitudinal*dt/.43;else w.children.forEach(c=>{if(c instanceof T.Mesh&&c.geometry.type==='BoxGeometry')c.rotation.x+=longitudinal*dt/.43})})}lat=lateral;applyCharacter();
  if(drifting&&frame%3===0){const sides=mode==='bike'?[0]:[-1,1],zOff=mode==='bike'?.95:1.5;for(const side of sides){const pos=new T.Vector3(side,.1,zOff).applyAxisAngle(new T.Vector3(0,1,0),yaw).add(driven.position);const puff=smoke[smokeIndex++%smoke.length];puff.s.position.copy(pos);puff.life=1;puff.s.scale.setScalar(mode==='bike'?.85:.6);const skid=skids[skidIndex++%skids.length];skid.visible=true;skid.position.set(pos.x,driven.position.y+.027,pos.z);skid.rotation.z=-Math.atan2(vx,vz)}}
if(frame%6===0)emit(drifting,slipAngle);if(osc&&gain&&audio){osc.frequency.setTargetAtTime((biking?52:32)+speed*(biking?3.1:2.4)+(keys.W?20:0),audio.currentTime,.08);gain.gain.setTargetAtTime(muted?0:.025+(keys.W?.025:0),audio.currentTime,.1)}applyCharacter();
  }
 function loop(now:number){if(disposed)return;const dt=Math.min((now-clock)/1000||.016,.05);clock=now;frame++;if(keys.Q)camOff-=.9*dt;camOff=((camOff+Math.PI)%6.283185307179586+6.283185307179586)%6.283185307179586-Math.PI;if(active&&!paused){accum+=dt;while(accum>=1/120){physics(1/120);accum-=1/120}}if(npcHit>0){npcHit-=dt;const spd=Math.hypot(vx,vz);if(spd>0){const dr=Math.exp(-dt*1.6);vx*=dr;vz*=dr}}for(const p of smoke){if(p.life>0&&!paused){p.life-=dt*.55;p.s.position.y+=dt*.6;p.s.scale.addScalar(dt*1.7);p.s.material.opacity=Math.max(0,p.life*.45)}}updateCamera(dt);const f=focus();if(npc&&active&&!paused){const prr=mode!=='foot'?(mode==='bike'?1.1:2.4):0;const colr=npc.update(dt,f.position.x,f.position.z,prr?vx:0,prr?vz:0,prr);if(prr&&(colr.px||colr.pz||colr.vx||colr.vz)){driven.position.x+=colr.px;driven.position.z+=colr.pz;vx+=colr.vx;vz+=colr.vz;if(Math.hypot(colr.vx,colr.vz)>1.5||Math.hypot(colr.px,colr.pz)>.1){combo=0;npcHit=.35}}}if(raceway.group.visible&&active&&!paused){const r=raceway.update(dt,f.position.x,f.position.z,driftingNow,clock);if(r&&(r.px||r.pz||r.ov>0)){const d=Math.hypot(r.px,r.pz);if(d>.001&&mode!=='foot'){driven.position.x+=r.px;driven.position.z+=r.pz;const nx=r.px/d,nz=r.pz/d,into=vx*nx+vz*nz;if(into>0&&driftingNow){vx-=nx*into*.9;vz-=nz*into*.9}}if(r.ov>0&&mode!=='foot'){score+=r.ov;combo+=r.ov;scoreQ+=r.ov;notice='OVERTAKE +'+r.ov+' PTS';noticeUntil=clock+1300;emit()}}}sun.position.set(f.position.x-90,80,f.position.z-130);sun.target.position.copy(f.position);sky.position.copy(camera.position);sunDisc.position.copy(camera.position).add(new T.Vector3(-440,105,-780));if(genActive()){for(const e of genTowns.values())e.town.update(clock*.001);if(frame%90===0)updateGenArea()}else town?.update(clock*.001);effects.render();raf=requestAnimationFrame(loop)}
 function pause(){if(!active)return;if(!paused&&!mapPausing)bankScore();paused=!paused;dragging=false;for(const k in keys)keys[k]=false;onPause(paused);  if(npc){if(paused)npc.despawn();else if(!interior){const ff=focus();npc.respawn(ff.position.x,ff.position.z);npc.spawnWild(ff.position.x,ff.position.z,isBikeId(selected))}}if(gain&&audio)gain.gain.setTargetAtTime(0,audio.currentTime,.03)}
  function setMapOpen(open:boolean){if(mapOpen===open)return;mapOpen=open;if(open){if(active&&!paused){pausedWithMap=true;mapPausing=true;pause();mapPausing=false}}else if(pausedWithMap){pausedWithMap=false;pause()}}
function key(k:string,down:boolean){if(k==='E'){if(down)interact();return}if(k==='G'){if(down)cycleStyle();return}if(k==='C'){if(down)camOff=0;return}keys[k]=down}
  function menu(){if(interior)leaveInterior();bankScore();active=false;paused=false;showVehicles=false;renderVehicles();dragging=false;for(const k in keys)keys[k]=false;npc?.despawn();onPause(false);if(gain&&audio)gain.gain.setTargetAtTime(0,audio.currentTime,.03)}
 async function selectMap(id:MapId){if(interior)leaveInterior();if(id!=='coast'&&id!=='costco'&&id!=='raceway'&&!TOWN_MAPS.has(id))throw new Error('Unknown map');if(genWorld)teardownGen();if(TOWN_MAPS.has(id)&&!towns.get(id)){const data=await loadTownData(id);if(disposed)return;const t=createTown(data);towns.set(id,t);scene.add(t.group)}town=towns.get(id)??null;mapId=id;applyWorldVisibility();(scene.fog as T.FogExp2).density=TOWN_MAPS.has(id)?.0008:(id==='raceway'?.0012:.0025);npc?.destroy();npc=null;if(TOWN_MAPS.has(mapId)&&town)npc=createNpc({id:mapId,roads:town.data.roads,areas:town.data.areas,bounds:town.data.bounds,height:(x,z)=>town!.height(x,z),scene,low:LOW});if(mapId==='raceway'){raceway.reset()}interiorDoors=TOWN_MAPS.has(mapId)&&town?planInteriors(town.data,(x,z)=>town!.height(x,z)):[];bankScore();skids.forEach(s=>s.visible=false);smoke.forEach(p=>{p.life=0;p.s.material.opacity=0});reset()}
 const normalize=(code:string)=>code==='Space'?'SPACE':code.startsWith('Shift')?'Shift':code.replace('Key','').replace('ArrowUp','W').replace('ArrowDown','S').replace('ArrowLeft','A').replace('ArrowRight','D');
 function down(e:KeyboardEvent){if(!active)return;const k=normalize(e.code);if(['W','A','S','D','SPACE','Escape','R','E','G','Shift','Q','C'].includes(k)){e.preventDefault();if(k==='Escape'&&!e.repeat){if(!mapOpen)pause()}else if(k==='R'&&!e.repeat)reset();else if(k==='E'&&!e.repeat)interact();else if(k==='G'&&!e.repeat)cycleStyle();else if(k==='C'&&!e.repeat){camOff=0}else keys[k]=true}}
 function up(e:KeyboardEvent){keys[normalize(e.code)]=false}
 function blur(){for(const k in keys)keys[k]=false}
 function pointerDown(e:PointerEvent){if(active&&!paused){dragging=true;lastPointerX=e.clientX;renderer.domElement.setPointerCapture(e.pointerId)}}
 function pointerMove(e:PointerEvent){if(dragging){const delta=(e.clientX-lastPointerX)*.006;if(mode==='foot')cameraOrbit-=delta;else camOff-=delta;lastPointerX=e.clientX}}
 function pointerUp(){dragging=false}
 function resize(){const w=Math.max(1,innerWidth),h=Math.max(1,innerHeight);camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setPixelRatio(LOW?1:Math.min(devicePixelRatio,1.5));renderer.setSize(w,h);effects.resize()}
 const lifecycle=new AbortController();const options={signal:lifecycle.signal};
 const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(context?.registerTool){try{Promise.resolve(context.registerTool({name:'reset_car',description:'Regroup the character and both vehicles at the map start, keeping the session score.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute(input:unknown){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object');reset();return{status:'reset',score:Math.floor(score)}}},options)).catch(()=>{})}catch{}}

  const setStartVehicle=(id:VehicleId)=>{selected=id;if(isBikeId(id)){if(id==='bike'){if(bmwGroup)mountBike(bmwGroup)}else{const m=bikeGarage[id];if(m)mountBike(m.group)}}renderVehicles();if(!active||mode!==(isBikeId(id)?'bike':'car'))reset()};
  window.addEventListener('keydown',down,options);window.addEventListener('keyup',up,options);window.addEventListener('blur',blur,options);window.addEventListener('resize',resize,options);document.addEventListener('visibilitychange',()=>{if(document.hidden&&active&&!paused)pause()},options);renderer.domElement.addEventListener('pointerdown',pointerDown,options);renderer.domElement.addEventListener('pointermove',pointerMove,options);renderer.domElement.addEventListener('pointerup',pointerUp,options);renderer.domElement.addEventListener('pointercancel',pointerUp,options);reset();raf=requestAnimationFrame(loop);
  const api={start(){active=true;paused=false;showVehicles=true;renderVehicles();ensureAudio();host.focus()},pause,reset,key,menu,selectMap,selectGenWorld,setStartVehicle,interact,setMapOpen,setSportMode(v:boolean){sportMode=v;bankScore();emit()},mute(m:boolean){muted=m},dispose(){teardownGen();npc?.destroy();npc=null;raceway.destroy();lifecycle.abort();disposed=true;cancelAnimationFrame(raf);void audio?.close();scene.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();const ms=Array.isArray(o.material)?o.material:[o.material];ms.forEach(m=>m.dispose());if(o instanceof T.InstancedMesh)o.dispose()}});smoke.forEach(p=>p.s.material.dispose());towns.forEach(t=>t.textures.forEach(tex=>tex.dispose()));motorbike.textures.forEach(t=>t.dispose());parking.textures.forEach(t=>t.dispose());roadGrain.dispose();Object.values(garage).forEach(v=>v?.textures.forEach(t=>t.dispose()));Object.values(bikeGarage).forEach(b=>{b?.group.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();const ms=Array.isArray(o.material)?o.material:[o.material];ms.forEach(m=>m.dispose())}})});if(bmwGroup)bmwGroup.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();const ms=Array.isArray(o.material)?o.material:[o.material];ms.forEach(m=>m.dispose())}});glbTextures.forEach(t=>t.dispose());smokeTex.dispose();env.dispose();effects.dispose();renderer.dispose();renderer.domElement.remove()}};
  (window as Window & {__race?:unknown}).__race=api;return api;
}
