import * as T from 'three';
import {grainTexture} from './visuals';
import {createTownDetails} from './town-details';
import { mergeGeometries } from 'three/addons/utils/BufferGeometryUtils.js';
import {type Point,type TownData} from './town-data';
export function inside(x:number,z:number,p:Point[]){let hit=false;for(let i=0,j=p.length-1;i<p.length;j=i++){const a=p[i],b=p[j];if((a[1]>z)!==(b[1]>z)&&x<(b[0]-a[0])*(z-a[1])/(b[1]-a[1])+a[0])hit=!hit}return hit}
export function makeHeight(data:TownData){const e=data.elev;if(!e)return()=>0;const{o,res,nx,nz,data:_}=e;return(x:number,z:number)=>{const fx=(x-o[0])/res,fz=(z-o[1])/res;let ix=Math.floor(fx),iz=Math.floor(fz);const tx=fx-ix,tz=fz-iz;ix=Math.max(0,Math.min(nx-2,ix));iz=Math.max(0,Math.min(nz-2,iz));const i=iz*nx+ix,v00=_[i],v10=_[i+1],v01=_[i+nx],v11=_[i+nx+1];if(tx+tz>=1)return(1-tx)*v01+(tx+tz-1)*v11+(1-tz)*v10;return(1-tx-tz)*v00+tx*v10+tz*v01}}
export function createTownCollider(data:TownData){
 const grid=new Map<string,number[]>();const cell=80;
 data.buildings.forEach((b,i)=>{const xs=b.p.map(p=>p[0]),zs=b.p.map(p=>p[1]);for(let x=Math.floor((Math.min(...xs)-3)/cell);x<=Math.floor((Math.max(...xs)+3)/cell);x++)for(let z=Math.floor((Math.min(...zs)-3)/cell);z<=Math.floor((Math.max(...zs)+3)/cell);z++){const key=x+','+z;const ids=grid.get(key)??[];ids.push(i);grid.set(key,ids)}});
 const water=data.areas.filter(a=>a.kind==='water');
 return(x:number,z:number,vx:number,vz:number,previous:Point,radius=2.2)=>{
  let hit=false;const [minX,minZ,maxX,maxZ]=data.bounds;
  if(x<minX||x>maxX){x=T.MathUtils.clamp(x,minX,maxX);vx*=-.2;hit=true}if(z<minZ||z>maxZ){z=T.MathUtils.clamp(z,minZ,maxZ);vz*=-.2;hit=true}
  for(const i of grid.get(Math.floor(x/cell)+','+Math.floor(z/cell))??[]){const p=data.buildings[i].p;let best=Infinity,qx=x,qz=z;for(let j=1;j<p.length;j++){const a=p[j-1],b=p[j],dx=b[0]-a[0],dz=b[1]-a[1];const u=T.MathUtils.clamp(((x-a[0])*dx+(z-a[1])*dz)/(dx*dx+dz*dz||1),0,1);const px=a[0]+u*dx,pz=a[1]+u*dz,d=(x-px)**2+(z-pz)**2;if(d<best){best=d;qx=px;qz=pz}}
   const within=inside(x,z,p);if(within||best<radius**2){let dx=within?qx-x:x-qx,dz=within?qz-z:z-qz;const length=Math.hypot(dx,dz);if(length<.0001){x=previous[0];z=previous[1];vx*=-.2;vz*=-.2;hit=true;continue}dx/=length;dz/=length;x=qx+dx*(radius+.05);z=qz+dz*(radius+.05);const into=vx*dx+vz*dz;if(into<0){vx-=dx*into*1.25;vz-=dz*into*1.25}hit=true}}
  if(water.some(a=>inside(x,z,a.p))){x=previous[0];z=previous[1];vx*=-.2;vz*=-.2;hit=true}
  return{x,z,vx,vz,hit};
 }
}
export function createTown(data:TownData){
 const group=new T.Group(),textures:T.Texture[]=[];const mat=(color:string,roughness=.85)=>new T.MeshStandardMaterial({color,roughness});
const land=mat('#788564'),grass=mat('#6a8057'),asphalt=mat('#3b4244'),path=mat('#a6a28b'),roofMat=mat('#606c70'),water= new T.MeshStandardMaterial({color:'#457e87',roughness:.27,metalness:.6});
  const ds=(m:T.MeshStandardMaterial)=>{m.side=T.DoubleSide;return m};ds(grass);ds(path);ds(roofMat);water.side=T.DoubleSide;
  const texture=grainTexture();texture.repeat.set(1,1);textures.push(texture);asphalt.map=texture;asphalt.bumpMap=texture;asphalt.bumpScale=.04;
  const batches=new Map<T.Material,T.BufferGeometry[]>();function add(g:T.BufferGeometry,m:T.Material){const list=batches.get(m)??[];list.push(g);batches.set(m,list)}
  const height=makeHeight(data);
  function drape(g:T.BufferGeometry,dy:number){const p=g.getAttribute('position')as T.BufferAttribute;for(let i=0;i<p.count;i++)p.setY(i,height(p.getX(i),p.getZ(i))+dy);p.needsUpdate=true;return g}
  function flat(p:Point[],off:number,m:T.Material){if(p.length<4)return;const shape=new T.Shape(p.map(q=>new T.Vector2(q[0],-q[1])));const g=new T.ShapeGeometry(shape);g.rotateX(-Math.PI/2);drape(g,off);add(g,m)}
  function clipToTri(poly:Point[],t:[Point,Point,Point]):Point[]{const s=(a:Point,b:Point,p:Point)=>(b[0]-a[0])*(p[1]-a[1])-(b[1]-a[1])*(p[0]-a[0]);let cur=poly;for(const [a,b,c]of[[t[0],t[1],t[2]],[t[1],t[2],t[0]],[t[2],t[0],t[1]]]as [Point,Point,Point][]){const cs=s(a,b,c)>=0;const out:Point[]=[];for(let i=0;i<cur.length;i++){const p=cur[i],q=cur[(i+1)%cur.length],sp=(s(a,b,p)>=0)===cs,sq=(s(a,b,q)>=0)===cs;if(sp&&sq){out.push(q);continue}if(!sp&&!sq)continue;const tp=s(a,b,p),tq=s(a,b,q),t2=tp/(tp-tq);out.push([p[0]+(q[0]-p[0])*t2,p[1]+(q[1]-p[1])*t2]);if(!sp)out.push(q)}cur=out}return cur}
  function pave(poly:Point[],dy:number,m:T.Material){if(poly.length<4)return;if(!data.elev)return flat(poly,dy,m);const{o,res,nx,nz}=data.elev;let mix=Infinity,miz=Infinity,mmx=-Infinity,mmz=-Infinity;for(const p of poly){if(p[0]<mix)mix=p[0];if(p[0]>mmx)mmx=p[0];if(p[1]<miz)miz=p[1];if(p[1]>mmz)mmz=p[1]}const ix0=Math.max(0,Math.floor((mix-o[0])/res)-1),ix1=Math.min(nx-2,Math.floor((mmx-o[0])/res)+1),iz0=Math.max(0,Math.floor((miz-o[1])/res)-1),iz1=Math.min(nz-2,Math.floor((mmz-o[1])/res)+1);const pos:number[]=[],uv:number[]=[],idx:number[]=[];for(let iz=iz0;iz<=iz1;iz++)for(let ix=ix0;ix<=ix1;ix++){const x0=o[0]+ix*res,z0=o[1]+iz*res,x1=x0+res,z1=z0+res;for(const t of[[[x0,z0],[x1,z0],[x0,z1]],[[x0,z1],[x1,z0],[x1,z1]]]as [Point,Point,Point][]){const inner=t.every(q=>inside(q[0],q[1],poly));let c:Point[];if(inner){const seen=new Map<string,number>();for(const q of t){const k=q[0].toFixed(3)+','+q[1].toFixed(3);if(!seen.has(k)){seen.set(k,pos.length/3);pos.push(q[0],height(q[0],q[1])+dy,q[1]);uv.push(q[0]/8,q[1]/8)}}const ids=[...seen.values()];if(ids.length===3)idx.push(ids[0],ids[1],ids[2]);continue}c=clipToTri(poly,t);if(c.length<3)continue;const u:Point[]=[];for(const p of c){const q=u[u.length-1];if(!q||q[0]!==p[0]||q[1]!==p[1])u.push(p)}if(u.length<3)continue;let faces:number[][];try{faces=T.ShapeUtils.triangulateShape(u.map(p=>new T.Vector2(p[0],p[1])),[])}catch{continue}if(!faces.length)continue;const base=pos.length/3;for(const p of u){const y=height(p[0],p[1])+dy;pos.push(p[0],y,p[1]);uv.push(p[0]/8,p[1]/8)}for(const f of faces)idx.push(base+f[0],base+f[1],base+f[2])}}if(!idx.length)return;const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(pos,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));const ax=pos[idx[0]*3],ay=pos[idx[0]*3+1],az=pos[idx[0]*3+2],bx=pos[idx[1]*3]-ax,by=pos[idx[1]*3+1]-ay,bz=pos[idx[1]*3+2]-az,cx=pos[idx[2]*3]-ax,cy=pos[idx[2]*3+1]-ay,cz=pos[idx[2]*3+2]-az;if((bz*cx-bx*cz)<=0){for(let i=0;i<idx.length;i+=3){const t=idx[i+1];idx[i+1]=idx[i+2];idx[i+2]=t}}g.setIndex(idx);g.computeVertexNormals();add(g,m)}
  function roof(p:Point[],baseY:number,m:T.Material){if(p.length<4)return;const shape=new T.Shape(p.map(q=>new T.Vector2(q[0],-q[1])));const g=new T.ShapeGeometry(shape);g.rotateX(-Math.PI/2);g.translate(0,baseY,0);add(g,m)}
if(data.elev){
    const {nx,nz,res,o}=data.elev,gwx=(nx-1)*res,gwz=(nz-1)*res;
    const gPos:number[]=[],gIdx:number[]=[];for(let iz=0;iz<nz;iz++)for(let ix=0;ix<nx;ix++){const x=o[0]+ix*res,z=o[1]+iz*res;gPos.push(x,height(x,z),z)}for(let iz=0;iz<nz-1;iz++)for(let ix=0;ix<nx-1;ix++){const i00=iz*nx+ix,i10=iz*nx+ix+1,i01=(iz+1)*nx+ix,i11=(iz+1)*nx+ix+1;gIdx.push(i00,i01,i10,i01,i11,i10)}const gg=new T.BufferGeometry();gg.setAttribute('position',new T.Float32BufferAttribute(gPos,3));gg.setIndex(gIdx);gg.computeVertexNormals();const ground=new T.Mesh(gg,land);ground.receiveShadow=true;ground.castShadow=false;ground.matrixAutoUpdate=false;group.add(ground);
   const table=new T.Mesh(new T.PlaneGeometry(20000,20000),land);table.rotation.x=-Math.PI/2;table.position.set(o[0]+gwx/2,-1.6,o[1]+gwz/2);table.receiveShadow=true;table.castShadow=false;group.add(table);
  }else{
   const ground=new T.Mesh(new T.PlaneGeometry(16000,16000,120,120),land);ground.rotation.x=-Math.PI/2;ground.position.set((data.bounds[0]+data.bounds[2])/2,-.18,(data.bounds[1]+data.bounds[3])/2);const gv=ground.geometry.getAttribute('position')as T.BufferAttribute;for(let i=0;i<gv.count;i++)gv.setY(i,height(gv.getX(i)+ground.position.x,gv.getZ(i)+ground.position.z)-.18);gv.needsUpdate=true;ground.geometry.computeVertexNormals();ground.receiveShadow=true;ground.castShadow=false;ground.matrixAutoUpdate=false;ground.updateMatrix();group.add(ground);
  }
for(const a of data.areas){if(a.kind==='water')flat(a.p,-.08,water);else if(['grass','forest','wood','park','meadow','recreation_ground','village_green','orchard','vineyard','farmland'].includes(a.kind))pave(a.p,.03,grass);else if(['pitch','parking','pedestrian'].includes(a.kind))pave(a.p,.035,path)}
  const roadSegments:{a:Point,b:Point,width:number}[]=[];
  for(const road of data.roads){const drivable=['residential','service','unclassified'].includes(road.kind)||['primary','secondary','tertiary','living_street'].includes(road.kind),w=road.width;for(let i=1;i<road.p.length;i++){const a=road.p[i-1],b=road.p[i],dx=b[0]-a[0],dz=b[1]-a[1],length=Math.hypot(dx,dz);if(length<.05)continue;const ux=dx/length,uz=dz/length,nx=-uz,nz=ux,hw=w/2,hl=length/2+.175,mx=(a[0]+b[0])/2,mz=(a[1]+b[1])/2;pave([[mx-ux*hl-nx*hw,mz-uz*hl-nz*hw],[mx+ux*hl-nx*hw,mz+uz*hl-nz*hw],[mx+ux*hl+nx*hw,mz+uz*hl+nz*hw],[mx-ux*hl+nx*hw,mz-uz*hl+nz*hw]],.06,drivable?asphalt:path);if(drivable){roadSegments.push({a,b,width:w});const pts:Point[]=[];for(let k=0;k<12;k++){const an=k/12*Math.PI*2;pts.push([a[0]+Math.cos(an)*w/2,a[1]+Math.sin(an)*w/2])}pave(pts,.08,asphalt)}}}
 const facades=['#c2beb0','#adbaa9','#c3af9c','#a7b4ba'].map((color,k)=>{const c=document.createElement('canvas');c.width=128;c.height=128;const ctx=c.getContext('2d')!;ctx.fillStyle=color;ctx.fillRect(0,0,128,128);ctx.fillStyle='#7f8987';ctx.fillRect(0,123,128,5);ctx.fillStyle='#e2ded0';ctx.fillRect(32,27,64,77);ctx.fillStyle=k===2?'#697e80':'#34535d';ctx.fillRect(37,32,54,67);ctx.fillStyle='#a6bbbc';ctx.fillRect(63,32,3,67);ctx.fillRect(37,62,54,3);const tx=new T.CanvasTexture(c);tx.wrapS=tx.wrapT=T.RepeatWrapping;tx.colorSpace=T.SRGBColorSpace;textures.push(tx);return new T.MeshStandardMaterial({map:tx,roughness:.85,side:T.DoubleSide})});
 const util=mat('#a4a599');util.side=T.DoubleSide;
 for(const b of data.buildings){const position:number[]=[],uv:number[]=[],idx:number[]=[];const base=height(((b.p.reduce((s,p)=>s+p[0],0))/b.p.length),((b.p.reduce((s,p)=>s+p[1],0))/b.p.length));for(let i=1;i<b.p.length;i++){const a=b.p[i-1],c=b.p[i],length=Math.hypot(c[0]-a[0],c[1]-a[1]);const n=position.length/3;position.push(a[0],base,a[1],c[0],base,c[1],a[0],base+b.h,a[1],c[0],base+b.h,c[1]);uv.push(0,0,length/3.8,0,0,b.h/3.1,length/3.8,b.h/3.1);idx.push(n,n+2,n+1,n+1,n+2,n+3)}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(position,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.setIndex(idx);g.computeVertexNormals();const g2=new T.BufferGeometry();g2.setAttribute('position',new T.Float32BufferAttribute([...position],3));g2.setAttribute('uv',new T.Float32BufferAttribute([...uv],2));g2.setIndex([...idx]);g2.computeVertexNormals();add(g,['garage','garages','greenhouse','ruins'].includes(b.kind)?util:facades[b.id%facades.length]);roof(b.p,base+b.h,roofMat)}
 for(const [material,geometries]of batches){if(!geometries.length)continue;const merged=mergeGeometries(geometries,false);if(!merged)throw new Error('Unable to assemble town geometry');const m=new T.Mesh(merged,material);m.castShadow=facades.includes(material as T.MeshStandardMaterial)||material===util;m.receiveShadow=true;group.add(m);geometries.forEach(g=>g.dispose())}
 const details=createTownDetails(data,inside,height);group.add(details.group);textures.push(...details.textures);
 const baseCollision=createTownCollider(data);const propGrid=new Map<string,typeof details.solids>();for(const p of details.solids){const key=Math.floor(p.x/20)+','+Math.floor(p.z/20),list=propGrid.get(key)??[];list.push(p);propGrid.set(key,list)}
 function collide(x:number,z:number,vx:number,vz:number,previous:Point,radius=2.2){let c=baseCollision(x,z,vx,vz,previous,radius);const cx=Math.floor(c.x/20),cz=Math.floor(c.z/20);for(let ix=cx-1;ix<=cx+1;ix++)for(let iz=cz-1;iz<=cz+1;iz++)for(const p of propGrid.get(ix+','+iz)??[]){let dx=c.x-p.x,dz=c.z-p.z,d=Math.hypot(dx,dz);if(d<radius+p.r){if(d<.0001){dx=1;dz=0;d=1}const nx=dx/d,nz=dz/d;c.x=p.x+nx*(radius+p.r+.02);c.z=p.z+nz*(radius+p.r+.02);const into=c.vx*nx+c.vz*nz;if(into<0){c.vx-=into*nx*1.2;c.vz-=into*nz*1.2}c.hit=true}}return c}

  return{group,textures,data,collide,update:details.update,stats:details.stats,height};
}