'use client';
import {useEffect,useRef} from 'react';
import {loadTownData,type TownData} from './town-data';
type Props={x:number,z:number,yaw:number,carX:number,carZ:number,bikeX:number,bikeZ:number,map?:string};
type View={cx:number,cy:number,scale:number,yaw:number,px:number,pz:number};
const T=(cx:number,cy:number,scale:number,yaw:number,px:number,pz:number):View=>({cx,cy,scale,yaw,px,pz});
const toScreen=([x,z]:[number,number],v:View):[number,number]=>{const dx=x-v.px,dz=z-v.pz;return[v.cx+(dx*Math.cos(-v.yaw)-dz*Math.sin(-v.yaw))*v.scale,v.cy+(dx*Math.sin(-v.yaw)+dz*Math.cos(-v.yaw))*v.scale]};
function buildView(d:TownData,full:boolean|undefined,x:number,z:number,cw:number,ch:number):View{if(full)return T(cw/2,ch/2,Math.min(cw/(d.bounds[2]-d.bounds[0]),ch/(d.bounds[3]-d.bounds[1]))*.94,0,(d.bounds[0]+d.bounds[2])/2,(d.bounds[1]+d.bounds[3])/2);return T(cw/2,ch/2,cw/310,0,x,z)}
function draw(ctx:CanvasRenderingContext2D,d:TownData,v:View,full:boolean|undefined){const w=ctx.canvas.width,h=ctx.canvas.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#0d1a21';ctx.fillRect(0,0,w,h);ctx.save();if(!full){ctx.beginPath();ctx.arc(v.cx,v.cy,Math.min(w,h)/2-4,0,Math.PI*2);ctx.clip()}for(const a of d.areas){if(!['water','park','grass','forest','meadow','recreation_ground','village_green','orchard','vineyard','farmland','pitch'].includes(a.kind))continue;const pts=a.p.map(p=>toScreen(p,v));ctx.beginPath();pts.forEach((q,i)=>i?ctx.lineTo(q[0],q[1]):ctx.moveTo(q[0],q[1]));ctx.closePath();ctx.fillStyle=a.kind==='water'?'#2b5865':full?'#1c2d28':'#1f3129';ctx.fill()}for(const r of d.roads){const pts=r.p.map(p=>toScreen(p,v));ctx.beginPath();pts.forEach((q,i)=>i?ctx.lineTo(q[0],q[1]):ctx.moveTo(q[0],q[1]));ctx.strokeStyle=r.kind==='residential'?(full?'#a9b8a2':'#b3c4ab'):full?'#5c7678':'#6d8583';ctx.lineWidth=r.kind==='residential'?(full?1.4:2.2):full?.6:.9;ctx.lineCap='round';ctx.stroke()}if(full){ctx.strokeStyle='#394b48';ctx.lineWidth=.7;for(const b of d.buildings){ctx.beginPath();b.p.forEach((q,i)=>{const t=toScreen(q,v);if(i)ctx.lineTo(t[0],t[1]);else ctx.moveTo(t[0],t[1])});ctx.closePath();ctx.stroke()}}ctx.restore();ctx.strokeStyle='#4a5b55';ctx.lineWidth=1;ctx.beginPath();ctx.arc(v.cx,v.cy,Math.min(w,h)/2-4,0,Math.PI*2);ctx.stroke()}
function markersDraw(ctx:CanvasRenderingContext2D,d:TownData,v:View,p:Props){for(const[px,pz,col,lab]of[[p.carX,p.carZ,'#e5eade','C'],[p.bikeX,p.bikeZ,'#74c0f9','B']]as[number,number,string,string][]){const s=toScreen([px,pz],v);ctx.fillStyle=col;ctx.fillRect(s[0]-2.5,s[1]-2.5,5,5);ctx.font='700 9px Arial';ctx.fillText(lab,s[0]+6,s[1]+3)}ctx.save();ctx.translate(v.cx,v.cy);ctx.rotate(-p.yaw);ctx.beginPath();ctx.moveTo(0,-9);ctx.lineTo(5,6);ctx.lineTo(0,2.5);ctx.lineTo(-5,6);ctx.closePath();ctx.fillStyle='#dbfd85';ctx.shadowColor='#dbfd85';ctx.shadowBlur=9;ctx.fill();ctx.restore()}
export function TownMinimap(p:Props){const canvas=useRef<HTMLCanvasElement>(null),data=useRef<TownData|null>(null),pos=useRef(p);pos.current=p;useEffect(()=>{let ok=true;void loadTownData(p.map||'svitlodarsk').then(d=>{if(ok)data.current=d}).catch(()=>{});const t=setInterval(()=>{if(!canvas.current||!data.current)return;const c=canvas.current,ctx=c.getContext('2d')!,d=data.current,q=pos.current,v=buildView(d,false,q.x,q.z,c.width,c.height);draw(ctx,d,v,false);markersDraw(ctx,d,v,q)},100);return()=>{ok=false;clearInterval(t)}},[p.map]);return<canvas ref={canvas} width={240} height={240} className="mini-canvas" aria-label="Town map following your position"/>}
export function TownFullMap(p:Props){const canvas=useRef<HTMLCanvasElement>(null),base=useRef<HTMLCanvasElement|null>(null),data=useRef<TownData|null>(null),pos=useRef(p);pos.current=p;useEffect(()=>{let ok=true;void loadTownData(p.map||'svitlodarsk').then(d=>{if(!ok)return;data.current=d;const c=document.createElement('canvas');c.width=720;c.height=640;draw(c.getContext('2d')!,d,buildView(d,true,p.x,p.z,c.width,c.height),true);base.current=c}).catch(()=>{});const t=setInterval(()=>{if(!canvas.current||!base.current||!data.current)return;const c=canvas.current,ctx=c.getContext('2d')!,d=data.current,q=pos.current;ctx.drawImage(base.current,0,0);const v=buildView(d,true,q.x,q.z,c.width,c.height);for(const[px,pz,col,lab]of[[q.carX,q.carZ,'#e5eade','CAR'],[q.bikeX,q.bikeZ,'#74c0f9','BIKE']]as[number,number,string,string][]){const s=toScreen([px,pz],v);ctx.save();ctx.translate(s[0],s[1]);ctx.strokeStyle='#0d1a21';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,5,0,Math.PI*2);ctx.stroke();ctx.fillStyle=col;ctx.fill();ctx.restore();ctx.font='700 9px Arial';ctx.textAlign='center';ctx.strokeStyle='#0d1a21';ctx.lineWidth=3;ctx.strokeText(lab,s[0],s[1]-9);ctx.fillStyle=col;ctx.fillText(lab,s[0],s[1]-9)}const s=toScreen([q.x,q.z],v);ctx.save();ctx.translate(s[0],s[1]);ctx.rotate(-q.yaw);ctx.beginPath();ctx.moveTo(0,-13);ctx.lineTo(7,8);ctx.lineTo(0,3.5);ctx.lineTo(-7,8);ctx.closePath();ctx.fillStyle='#dbfd85';ctx.strokeStyle='#0d1a21';ctx.lineWidth=2;ctx.fill();ctx.stroke();ctx.restore()},100);return()=>{ok=false;clearInterval(t)}},[p.map]);return<canvas ref={canvas} width={720} height={640} className="full-canvas" aria-label="Full map with your position"/>}